import 'package:dash_flags/dash_flags.dart';
import 'package:donation_app_v1/const_values/title_values.dart';

enum Languages {
  english(code: 'en', name: 'English', country: Country.us),
  spanish(code: 'es', name: 'Español', country: Country.es),
  french(code: 'fr', name: 'Français', country: Country.fr),
  german(code: 'de', name: 'Deutsch', country: Country.de),
  italian(code: 'it', name: 'Italiano', country: Country.it),
  portuguese(code: 'pt', name: 'Português', country: Country.pt),
  dutch(code: 'nl', name: 'Nederlands', country: Country.nl),
  russian(code: 'ru', name: 'Русский', country: Country.ru),
  chinese(code: 'zh', name: '中文', country: Country.cn),
  japanese(code: 'ja', name: '日本語', country: Country.jp),
  korean(code: 'ko', name: '한국어', country: Country.kr),
  arabic(code: 'ar', name: 'العربية', country: Country.sa),
  hindi(code: 'hi', name: 'हिन्दी', country: Country.c_in),
  turkish(code: 'tr', name: 'Türkçe', country: Country.tr),
  thai(code: 'th', name: 'ไทย', country: Country.th),
  swedish(code: 'sv', name: 'Svenska', country: Country.se),
  greek(code: 'el', name: 'Ελληνικά', country: Country.gr),
  polish(code: 'pl', name: 'Polski', country: Country.pl),
  vietnamese(code: 'vi', name: 'Tiếng Việt', country: Country.vn);

  final String code;
  final String name;
  final Country country;

  const Languages({required this.code, required this.name, required this.country});

  static Languages fromCode(String code) {
    return Languages.values.firstWhere((lang) => lang.code == code, orElse: () => Languages.english);
  }
}
class AppStrings {
  static Map<String, Map<String, String>> translations = {
    // English (en)
    'en': {

      'title': 'Hello',
      'welcome': 'Welcome to my app!',
      'goodbye': 'Goodbye',
      'thank_you': 'Thank you!',
      'error': 'An error occurred. Please try again.',
      'greeting': 'Hello, {name}!',
      // Donation-specific keys
      'donation': 'Donation',
      'donate_now': 'Donate Now',
      'donation_history': 'Donation History',
      'enter_amount': 'Enter Amount',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'success': 'Success!',
      'donation_message': 'Your donation makes a difference.',
      'description': 'Description',
      'thank_you_donation': 'Thank you for your generous donation!',
    },
    // Spanish (es)
    'es': {
      'title': 'Hola',
      'welcome': '¡Bienvenido a mi aplicación!',
      'goodbye': 'Adiós',
      'thank_you': '¡Gracias!',
      'error': 'Ocurrió un error. Por favor, inténtalo de nuevo.',
      'greeting': '¡Hola, {name}!',
      // Donation-specific keys
      'donation': 'Donación',
      'donate_now': 'Donar Ahora',
      'donation_history': 'Historial de Donaciones',
      'enter_amount': 'Ingrese la Cantidad',
      'confirm': 'Confirmar',
      'cancel': 'Cancelar',
      'success': '¡Éxito!',
      'donation_message': 'Tu donación hace la diferencia.',
      'description': 'Descripción',
      'thank_you_donation': '¡Gracias por tu generosa donación!',
    },
    // French (fr)
    'fr': {
      'title': 'Bonjour',
      'welcome': 'Bienvenue dans mon application!',
      'goodbye': 'Au revoir',
      'thank_you': 'Merci!',
      'error': 'Une erreur est survenue. Veuillez réessayer.',
      'greeting': 'Bonjour, {name}!',
      // Donation-specific keys
      'donation': 'Don',
      'donate_now': 'Faire un Don',
      'donation_history': 'Historique des Dons',
      'enter_amount': 'Entrez le Montant',
      'confirm': 'Confirmer',
      'cancel': 'Annuler',
      'success': 'Succès!',
      'donation_message': 'Votre don fait la différence.',
      'description': 'Description',
      'thank_you_donation': 'Merci pour votre généreux don!',
    },
    // German (de)
    'de': {
      'title': 'Hallo',
      'welcome': 'Willkommen in meiner App!',
      'goodbye': 'Auf Wiedersehen',
      'thank_you': 'Danke!',
      'error': 'Ein Fehler ist aufgetreten. Bitte versuche es erneut.',
      'greeting': 'Hallo, {name}!',
      // Donation-specific keys
      'donation': 'Spende',
      'donate_now': 'Jetzt Spenden',
      'donation_history': 'Spendenhistorie',
      'enter_amount': 'Betrag eingeben',
      'confirm': 'Bestätigen',
      'cancel': 'Abbrechen',
      'success': 'Erfolg!',
      'donation_message': 'Ihre Spende macht einen Unterschied.',
      'description': 'Beschreibung',
      'thank_you_donation': 'Vielen Dank für Ihre großzügige Spende!',
    },
    // Italian (it)
    'it': {
      'title': 'Ciao',
      'welcome': 'Benvenuto nella mia app!',
      'goodbye': 'Arrivederci',
      'thank_you': 'Grazie!',
      'error': 'Si è verificato un errore. Per favore riprova.',
      'greeting': 'Ciao, {name}!',
      // Donation-specific keys
      'donation': 'Donazione',
      'donate_now': 'Dona Ora',
      'donation_history': 'Storico Donazioni',
      'enter_amount': 'Inserisci l\'Importo',
      'confirm': 'Conferma',
      'cancel': 'Annulla',
      'success': 'Successo!',
      'donation_message': 'La tua donazione fa la differenza.',
      'description': 'Descrizione',
      'thank_you_donation': 'Grazie per la tua generosa donazione!',
    },
    // Portuguese (pt)
    'pt': {

      'title': 'Olá',
      'welcome': 'Bem-vindo ao meu aplicativo!',
      'goodbye': 'Adeus',
      'thank_you': 'Obrigado!',
      'error': 'Ocorreu um erro. Por favor, tente novamente.',
      'greeting': 'Olá, {name}!',
      // Donation-specific keys
      'donation': 'Doação',
      'donate_now': 'Doe Agora',
      'donation_history': 'Histórico de Doações',
      'enter_amount': 'Digite o Valor',
      'confirm': 'Confirmar',
      'cancel': 'Cancelar',
      'success': 'Sucesso!',
      'donation_message': 'Sua doação faz a diferença.',
      'description': 'Descrição',
      'thank_you_donation': 'Obrigado por sua generosa doação!',
    },
    // Dutch (nl)
    'nl': {
      'title': 'Hallo',
      'welcome': 'Welkom in mijn app!',
      'goodbye': 'Tot ziens',
      'thank_you': 'Dank je!',
      'error': 'Er is een fout opgetreden. Probeer het opnieuw.',
      'greeting': 'Hallo, {name}!',
      // Donation-specific keys
      'donation': 'Donatie',
      'donate_now': 'Doneer Nu',
      'donation_history': 'Donatiegeschiedenis',
      'enter_amount': 'Voer Bedrag In',
      'confirm': 'Bevestigen',
      'cancel': 'Annuleren',
      'success': 'Succes!',
      'donation_message': 'Jouw donatie maakt een verschil.',
      'description': 'Beschrijving',
      'thank_you_donation': 'Bedankt voor je gulle donatie!',
    },
    // Russian (ru)
    'ru': {
      'title': 'Привет',
      'welcome': 'Добро пожаловать в мое приложение!',
      'goodbye': 'До свидания',
      'thank_you': 'Спасибо!',
      'error': 'Произошла ошибка. Пожалуйста, попробуйте еще раз.',
      'greeting': 'Привет, {name}!',
      // Donation-specific keys
      'donation': 'Пожертвование',
      'donate_now': 'Пожертвовать сейчас',
      'donation_history': 'История пожертвований',
      'enter_amount': 'Введите сумму',
      'confirm': 'Подтвердить',
      'cancel': 'Отмена',
      'success': 'Успех!',
      'donation_message': 'Ваше пожертвование имеет значение.',
      'description': 'Описание',
      'thank_you_donation': 'Спасибо за ваше щедрое пожертвование!',
    },
    // Chinese (zh)
    'zh': {
      'title': '你好',
      'welcome': '欢迎使用我的应用程序！',
      'goodbye': '再见',
      'thank_you': '谢谢！',
      'error': '发生错误。请再试一次。',
      'greeting': '你好, {name}!',
      // Donation-specific keys
      'donation': '捐款',
      'donate_now': '立即捐款',
      'donation_history': '捐款记录',
      'enter_amount': '输入金额',
      'confirm': '确认',
      'cancel': '取消',
      'success': '成功！',
      'donation_message': '您的捐款至关重要。',
      'description': '描述',
      'thank_you_donation': '感谢您的慷慨捐赠！',
    },
    // Japanese (ja)
    'ja': {
      'title': 'こんにちは',
      'welcome': '私のアプリへようこそ！',
      'goodbye': 'さようなら',
      'thank_you': 'ありがとう！',
      'error': 'エラーが発生しました。もう一度お試しください。',
      'greeting': 'こんにちは、{name}！',
      // Donation-specific keys
      'donation': '寄付',
      'donate_now': '今すぐ寄付',
      'donation_history': '寄付履歴',
      'enter_amount': '金額を入力',
      'confirm': '確認',
      'cancel': 'キャンセル',
      'success': '成功！',
      'donation_message': 'あなたの寄付が変化をもたらします。',
      'description': '説明',
      'thank_you_donation': 'ご寄付いただき、ありがとうございます！',
    },
    // Korean (ko)
    'ko': {
      'title': '안녕하세요',
      'welcome': '내 앱에 오신 것을 환영합니다!',
      'goodbye': '안녕히 가세요',
      'thank_you': '감사합니다!',
      'error': '오류가 발생했습니다. 다시 시도해주세요.',
      'greeting': '안녕하세요, {name}님!',
      // Donation-specific keys
      'donation': '기부',
      'donate_now': '지금 기부하기',
      'donation_history': '기부 내역',
      'enter_amount': '금액 입력',
      'confirm': '확인',
      'cancel': '취소',
      'success': '성공!',
      'donation_message': '여러분의 기부가 큰 변화를 만듭니다.',
      'description': '설명',
      'thank_you_donation': '여러분의 아낌없는 기부에 감사드립니다!',
    },
    // Arabic (ar)
    'ar': {
      'title': 'مرحبا',
      'welcome': 'أهلا بك في تطبيقي!',
      'goodbye': 'مع السلامة',
      'thank_you': 'شكرا!',
      'error': 'حدث خطأ. يرجى المحاولة مرة أخرى.',
      'greeting': 'مرحبا، {name}!',
      // Donation-specific keys
      'donation': 'تبرع',
      'donate_now': 'تصدق الآن',
      'donation_history': 'سجل التبرعات',
      'enter_amount': 'أدخل المبلغ',
      'confirm': 'تأكيد',
      'cancel': 'إلغاء',
      'success': 'نجاح!',
      'donation_message': 'تبرعك يحدث فرقًا.',
      'description': 'الوصف',
      'thank_you_donation': 'شكراً لتبرعك السخي!',
    },
    // Hindi (hi)
    'hi': {
      'title': 'नमस्ते',
      'welcome': 'मेरे ऐप में आपका स्वागत है!',
      'goodbye': 'अलविदा',
      'thank_you': 'धन्यवाद!',
      'error': 'एक त्रुटि हुई। कृपया पुन: प्रयास करें।',
      'greeting': 'नमस्ते, {name}!',
      // Donation-specific keys
      'donation': 'दान',
      'donate_now': 'अब दान करें',
      'donation_history': 'दान इतिहास',
      'enter_amount': 'राशि दर्ज करें',
      'confirm': 'पुष्टि करें',
      'cancel': 'रद्द करें',
      'success': 'सफलता!',
      'donation_message': 'आपका दान फर्क डालता है।',
      'description': 'विवरण',
      'thank_you_donation': 'आपके उदार दान के लिए धन्यवाद!',
    },
    // Turkish (tr)
    'tr': {
      'title': 'Merhaba',
      'welcome': 'Uygulamama hoş geldiniz!',
      'goodbye': 'Hoşçakal',
      'thank_you': 'Teşekkürler!',
      'error': 'Bir hata oluştu. Lütfen tekrar deneyin.',
      'greeting': 'Merhaba, {name}!',
      // Donation-specific keys
      'donation': 'Bağış',
      'donate_now': 'Şimdi Bağış Yap',
      'donation_history': 'Bağış Geçmişi',
      'enter_amount': 'Tutarı Girin',
      'confirm': 'Onayla',
      'cancel': 'İptal',
      'success': 'Başarılı!',
      'donation_message': 'Bağışınız fark yaratıyor.',
      'description': 'Açıklama',
      'thank_you_donation': 'Cömert bağışınız için teşekkürler!',
    },
    // Thai (th)
    'th': {
      'title': 'สวัสดี',
      'welcome': 'ยินดีต้อนรับสู่แอปของฉัน!',
      'goodbye': 'ลาก่อน',
      'thank_you': 'ขอบคุณ!',
      'error': 'เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง',
      'greeting': 'สวัสดี, {name}!',
      // Donation-specific keys
      'donation': 'บริจาค',
      'donate_now': 'บริจาคตอนนี้',
      'donation_history': 'ประวัติการบริจาค',
      'enter_amount': 'กรอกจำนวนเงิน',
      'confirm': 'ยืนยัน',
      'cancel': 'ยกเลิก',
      'success': 'สำเร็จ!',
      'donation_message': 'การบริจาคของคุณทำให้เกิดความเปลี่ยนแปลง',
      'description': 'รายละเอียด',
      'thank_you_donation': 'ขอบคุณสำหรับการบริจาคที่เอื้อเฟื้อของคุณ!',
    },
    // Swedish (sv)
    'sv': {
      'title': 'Hej',
      'welcome': 'Välkommen till min app!',
      'goodbye': 'Adjö',
      'thank_you': 'Tack!',
      'error': 'Ett fel inträffade. Försök igen, tack.',
      'greeting': 'Hej, {name}!',
      // Donation-specific keys
      'donation': 'Donation',
      'donate_now': 'Donera Nu',
      'donation_history': 'Donationshistorik',
      'enter_amount': 'Ange Belopp',
      'confirm': 'Bekräfta',
      'cancel': 'Avbryt',
      'success': 'Framgång!',
      'donation_message': 'Din donation gör skillnad.',
      'description': 'Beskrivning',
      'thank_you_donation': 'Tack för din generösa donation!',
    },
    // Greek (el)
    'el': {
      'title': 'Γειά σου',
      'welcome': 'Καλώς ήρθατε στην εφαρμογή μου!',
      'goodbye': 'Αντίο',
      'thank_you': 'Ευχαριστώ!',
      'error': 'Παρουσιάστηκε σφάλμα. Παρακαλώ δοκιμάστε ξανά.',
      'greeting': 'Γειά σου, {name}!',
      // Donation-specific keys
      'donation': 'Δωρεά',
      'donate_now': 'Δωρίστε Τώρα',
      'donation_history': 'Ιστορικό Δωρεών',
      'enter_amount': 'Εισάγετε Ποσό',
      'confirm': 'Επιβεβαίωση',
      'cancel': 'Ακύρωση',
      'success': 'Επιτυχία!',
      'donation_message': 'Η δωρεά σας κάνει τη διαφορά.',
      'description': 'Περιγραφή',
      'thank_you_donation': 'Σας ευχαριστούμε για την γενναιόδωρη δωρεά!',
    },
    // Polish (pl)
    'pl': {
      'title': 'Cześć',
      'welcome': 'Witamy w mojej aplikacji!',
      'goodbye': 'Do widzenia',
      'thank_you': 'Dziękuję!',
      'error': 'Wystąpił błąd. Spróbuj ponownie.',
      'greeting': 'Cześć, {name}!',
      // Donation-specific keys
      'donation': 'Darowizna',
      'donate_now': 'Przekaż Darowiznę',
      'donation_history': 'Historia Darowizn',
      'enter_amount': 'Wprowadź Kwotę',
      'confirm': 'Potwierdź',
      'cancel': 'Anuluj',
      'success': 'Sukces!',
      'donation_message': 'Twoja darowizna ma znaczenie.',
      'description': 'Opis',
      'thank_you_donation': 'Dziękujemy za Twoją hojność!',
    },
    // Vietnamese (vi)
    'vi': {
      'title': 'Xin chào',
      'welcome': 'Chào mừng bạn đến với ứng dụng của tôi!',
      'goodbye': 'Tạm biệt',
      'thank_you': 'Cảm ơn bạn!',
      'error': 'Đã xảy ra lỗi. Vui lòng thử lại.',
      'greeting': 'Xin chào, {name}!',
      // Donation-specific keys
      'donation': 'Quyên góp',
      'donate_now': 'Quyên góp ngay',
      'donation_history': 'Lịch sử quyên góp',
      'enter_amount': 'Nhập số tiền',
      'confirm': 'Xác nhận',
      'cancel': 'Hủy',
      'success': 'Thành công!',
      'donation_message': 'Sự quyên góp của bạn thật có ý nghĩa.',
      'description': 'Mô tả',
      'thank_you_donation': 'Cảm ơn bạn đã quyên góp hào phóng!',
    },
  };
  static String getText(String key, String langCode) {
    return translations[langCode]?[key] ?? key;
  }
}
