


class MenuTiles {
  static Map<String, Map<String, String>> labels = {
    // English (en)
    'en': {
      'home_tile': 'Home',
      'profile_tile': 'Profile',
      'about_us_tile': 'About & Contact Us',
      'qr_tile': 'Scan QR',
      'feedback_tile': 'Feedback',
      'settings_tile': 'Settings',
      'logout_tile': 'Log Out',
      'privacy_security_tile': 'Privacy & Security',
      'terms_conditions_tile': 'Terms & Conditions',
      'partners_tile': 'Partners',
      'help_support_tile': 'Help & Support',
      'main_category': 'Main',
      'settings_category': 'Settings',
      'support_info_category': 'Category & Info',
    },
    // Spanish (es)
    'es': {
      'home_tile': 'Inicio',
      'profile_tile': 'Perfil',
      'about_us_tile': 'Acerca & Contacto',
      'qr_tile': 'Escanear QR',
      'feedback_tile': 'Comentarios',
      'settings_tile': 'Configuración',
      'logout_tile': 'Cerrar Sesión',
      'privacy_security_tile': 'Privacidad & Seguridad',
      'terms_conditions_tile': 'Términos & Condiciones',
      'partners_tile': 'Socios',
      'help_support_tile': 'Ayuda & Soporte',
      'main_category': 'Principal',
      'settings_category': 'Configuración',
      'support_info_category': 'Categoría & Información',
    },
    // French (fr)
    'fr': {
      'home_tile': 'Accueil',
      'profile_tile': 'Profil',
      'about_us_tile': 'À Propos & Contact',
      'qr_tile': 'Scanner QR',
      'feedback_tile': 'Retour d’Information',
      'settings_tile': 'Paramètres',
      'logout_tile': 'Se Déconnecter',
      'privacy_security_tile': 'Confidentialité & Sécurité',
      'terms_conditions_tile': 'Conditions & Termes',
      'partners_tile': 'Partenaires',
      'help_support_tile': 'Aide & Support',
      'main_category': 'Principal',
      'settings_category': 'Paramètres',
      'support_info_category': 'Catégorie & Info',
    },
    // German (de)
    'de': {
      'home_tile': 'Startseite',
      'profile_tile': 'Profil',
      'about_us_tile': 'Über & Kontakt',
      'qr_tile': 'QR scannen',
      'feedback_tile': 'Feedback',
      'settings_tile': 'Einstellungen',
      'logout_tile': 'Abmelden',
      'privacy_security_tile': 'Datenschutz & Sicherheit',
      'terms_conditions_tile': 'AGB',
      'partners_tile': 'Partner',
      'help_support_tile': 'Hilfe & Support',
      'main_category': 'Haupt',
      'settings_category': 'Einstellungen',
      'support_info_category': 'Kategorie & Info',
    },
    // Italian (it)
    'it': {
      'home_tile': 'Home',
      'profile_tile': 'Profilo',
      'about_us_tile': 'Informazioni & Contatti',
      'qr_tile': 'Scansiona QR',
      'feedback_tile': 'Feedback',
      'settings_tile': 'Impostazioni',
      'logout_tile': 'Disconnetti',
      'privacy_security_tile': 'Privacy & Sicurezza',
      'terms_conditions_tile': 'Termini & Condizioni',
      'partners_tile': 'Partner',
      'help_support_tile': 'Aiuto & Supporto',
      'main_category': 'Principale',
      'settings_category': 'Impostazioni',
      'support_info_category': 'Categoria & Info',
    },
    // Portuguese (pt)
    'pt': {
      'home_tile': 'Início',
      'profile_tile': 'Perfil',
      'about_us_tile': 'Sobre & Contato',
      'qr_tile': 'Escanear QR',
      'feedback_tile': 'Feedback',
      'settings_tile': 'Configurações',
      'logout_tile': 'Sair',
      'privacy_security_tile': 'Privacidade & Segurança',
      'terms_conditions_tile': 'Termos & Condições',
      'partners_tile': 'Parceiros',
      'help_support_tile': 'Ajuda & Suporte',
      'main_category': 'Principal',
      'settings_category': 'Configurações',
      'support_info_category': 'Categoria & Info',
    },
    // Dutch (nl)
    'nl': {
      'home_tile': 'Home',
      'profile_tile': 'Profiel',
      'about_us_tile': 'Over & Contact',
      'qr_tile': 'QR scannen',
      'feedback_tile': 'Feedback',
      'settings_tile': 'Instellingen',
      'logout_tile': 'Uitloggen',
      'privacy_security_tile': 'Privacy & Veiligheid',
      'terms_conditions_tile': 'Voorwaarden',
      'partners_tile': 'Partners',
      'help_support_tile': 'Hulp & Ondersteuning',
      'main_category': 'Hoofd',
      'settings_category': 'Instellingen',
      'support_info_category': 'Categorie & Info',
    },
    // Russian (ru)
    'ru': {
      'home_tile': 'Главная',
      'profile_tile': 'Профиль',
      'about_us_tile': 'О нас & Контакты',
      'qr_tile': 'Сканировать QR',
      'feedback_tile': 'Обратная связь',
      'settings_tile': 'Настройки',
      'logout_tile': 'Выйти',
      'privacy_security_tile': 'Конфиденциальность & Безопасность',
      'terms_conditions_tile': 'Условия & Правила',
      'partners_tile': 'Партнеры',
      'help_support_tile': 'Помощь & Поддержка',
      'main_category': 'Основное',
      'settings_category': 'Настройки',
      'support_info_category': 'Категория & Инфо',
    },
    // Chinese (zh)
    'zh': {
      'home_tile': '主页',
      'profile_tile': '个人资料',
      'about_us_tile': '关于 & 联系我们',
      'qr_tile': '扫描二维码',
      'feedback_tile': '反馈',
      'settings_tile': '设置',
      'logout_tile': '退出',
      'privacy_security_tile': '隐私与安全',
      'terms_conditions_tile': '条款与条件',
      'partners_tile': '合作伙伴',
      'help_support_tile': '帮助与支持',
      'main_category': '主要',
      'settings_category': '设置',
      'support_info_category': '类别 & 信息',
    },
    // Japanese (ja)
    'ja': {
      'home_tile': 'ホーム',
      'profile_tile': 'プロフィール',
      'about_us_tile': 'お問い合わせ',
      'qr_tile': 'QRをスキャン',
      'feedback_tile': 'フィードバック',
      'settings_tile': '設定',
      'logout_tile': 'ログアウト',
      'privacy_security_tile': 'プライバシー & セキュリティ',
      'terms_conditions_tile': '利用規約',
      'partners_tile': 'パートナー',
      'help_support_tile': 'ヘルプ & サポート',
      'main_category': 'メイン',
      'settings_category': '設定',
      'support_info_category': 'カテゴリ & 情報',
    },
    // Korean (ko)
    'ko': {
      'home_tile': '홈',
      'profile_tile': '프로필',
      'about_us_tile': '소개 & 연락처',
      'qr_tile': 'QR 스캔',
      'feedback_tile': '피드백',
      'settings_tile': '설정',
      'logout_tile': '로그아웃',
      'privacy_security_tile': '개인정보 & 보안',
      'terms_conditions_tile': '이용약관',
      'partners_tile': '파트너',
      'help_support_tile': '도움말 & 지원',
      'main_category': '주요',
      'settings_category': '설정',
      'support_info_category': '카테고리 & 정보',
    },
    // Arabic (ar)
    'ar': {
      'home_tile': 'الرئيسية',
      'profile_tile': 'الملف الشخصي',
      'about_us_tile': 'حول & اتصل بنا',
      'qr_tile': 'مسح QR',
      'feedback_tile': 'الملاحظات',
      'settings_tile': 'الإعدادات',
      'logout_tile': 'تسجيل الخروج',
      'privacy_security_tile': 'الخصوصية & الأمان',
      'terms_conditions_tile': 'الشروط & الأحكام',
      'partners_tile': 'الشركاء',
      'help_support_tile': 'المساعدة & الدعم',
      'main_category': 'رئيسي',
      'settings_category': 'الإعدادات',
      'support_info_category': 'الفئة & المعلومات',
    },
    // Hindi (hi)
    'hi': {
      'home_tile': 'होम',
      'profile_tile': 'प्रोफ़ाइल',
      'about_us_tile': 'हमारे बारे में & संपर्क',
      'qr_tile': 'QR स्कैन करें',
      'feedback_tile': 'प्रतिक्रिया',
      'settings_tile': 'सेटिंग्स',
      'logout_tile': 'लॉग आउट',
      'privacy_security_tile': 'गोपनीयता & सुरक्षा',
      'terms_conditions_tile': 'नियम & शर्तें',
      'partners_tile': 'साझेदार',
      'help_support_tile': 'मदद & समर्थन',
      'main_category': 'मुख्य',
      'settings_category': 'सेटिंग्स',
      'support_info_category': 'श्रेणी & जानकारी',
    },
    // Turkish (tr)
    'tr': {
      'home_tile': 'Ana Sayfa',
      'profile_tile': 'Profil',
      'about_us_tile': 'Hakkımızda & İletişim',
      'qr_tile': 'QR Tara',
      'feedback_tile': 'Geri Bildirim',
      'settings_tile': 'Ayarlar',
      'logout_tile': 'Çıkış Yap',
      'privacy_security_tile': 'Gizlilik & Güvenlik',
      'terms_conditions_tile': 'Şartlar & Koşullar',
      'partners_tile': 'Ortaklar',
      'help_support_tile': 'Yardım & Destek',
      'main_category': 'Ana',
      'settings_category': 'Ayarlar',
      'support_info_category': 'Kategori & Bilgi',
    },
    // Thai (th)
    'th': {
      'home_tile': 'หน้าหลัก',
      'profile_tile': 'โปรไฟล์',
      'about_us_tile': 'เกี่ยวกับเรา & ติดต่อ',
      'qr_tile': 'สแกน QR',
      'feedback_tile': 'ข้อเสนอแนะ',
      'settings_tile': 'การตั้งค่า',
      'logout_tile': 'ออกจากระบบ',
      'privacy_security_tile': 'ความเป็นส่วนตัว & ความปลอดภัย',
      'terms_conditions_tile': 'ข้อกำหนด & เงื่อนไข',
      'partners_tile': 'พันธมิตร',
      'help_support_tile': 'ช่วยเหลือ & สนับสนุน',
      'main_category': 'หลัก',
      'settings_category': 'การตั้งค่า',
      'support_info_category': 'หมวด & ข้อมูล',
    },
    // Swedish (sv)
    'sv': {
      'home_tile': 'Hem',
      'profile_tile': 'Profil',
      'about_us_tile': 'Om & Kontakta Oss',
      'qr_tile': 'Skanna QR',
      'feedback_tile': 'Feedback',
      'settings_tile': 'Inställningar',
      'logout_tile': 'Logga Ut',
      'privacy_security_tile': 'Sekretess & Säkerhet',
      'terms_conditions_tile': 'Villkor',
      'partners_tile': 'Partners',
      'help_support_tile': 'Hjälp & Support',
      'main_category': 'Huvud',
      'settings_category': 'Inställningar',
      'support_info_category': 'Kategori & Info',
    },
    // Greek (el)
    'el': {
      'home_tile': 'Αρχική',
      'profile_tile': 'Προφίλ',
      'about_us_tile': 'Σχετικά & Επικοινωνία',
      'qr_tile': 'Σάρωση QR',
      'feedback_tile': 'Ανατροφοδότηση',
      'settings_tile': 'Ρυθμίσεις',
      'logout_tile': 'Αποσύνδεση',
      'privacy_security_tile': 'Απόρρητο & Ασφάλεια',
      'terms_conditions_tile': 'Όροι & Προϋποθέσεις',
      'partners_tile': 'Συνεργάτες',
      'help_support_tile': 'Βοήθεια & Υποστήριξη',
      'main_category': 'Κύρια',
      'settings_category': 'Ρυθμίσεις',
      'support_info_category': 'Κατηγορία & Πληροφορίες',
    },
    // Polish (pl)
    'pl': {
      'home_tile': 'Strona Główna',
      'profile_tile': 'Profil',
      'about_us_tile': 'O Nas & Kontakt',
      'qr_tile': 'Skanuj QR',
      'feedback_tile': 'Opinie',
      'settings_tile': 'Ustawienia',
      'logout_tile': 'Wyloguj',
      'privacy_security_tile': 'Prywatność & Bezpieczeństwo',
      'terms_conditions_tile': 'Regulamin',
      'partners_tile': 'Partnerzy',
      'help_support_tile': 'Pomoc & Wsparcie',
      'main_category': 'Główna',
      'settings_category': 'Ustawienia',
      'support_info_category': 'Kategoria & Info',
    },
    // Vietnamese (vi)
    'vi': {
      'home_tile': 'Trang Chủ',
      'profile_tile': 'Hồ Sơ',
      'about_us_tile': 'Về Chúng Tôi & Liên Hệ',
      'qr_tile': 'Quét QR',
      'feedback_tile': 'Phản Hồi',
      'settings_tile': 'Cài Đặt',
      'logout_tile': 'Đăng Xuất',
      'privacy_security_tile': 'Riêng Tư & Bảo Mật',
      'terms_conditions_tile': 'Điều Khoản & Điều Kiện',
      'partners_tile': 'Đối Tác',
      'help_support_tile': 'Trợ Giúp & Hỗ Trợ',
      'main_category': 'Chính',
      'settings_category': 'Cài Đặt',
      'support_info_category': 'Danh Mục & Thông Tin',
    },
  };

  static String getTile(String langCode, String key) {
    return labels[langCode]?[key] ?? key;
  }
}
