class FeedbackLabels{
  static Map<String, Map<String, String>> feedbackStrings = {
    'en': {
      'thanks_feedback': 'Thanks for your feedback!',
      'we_consider_text': 'We will consider it carefully.',
      'go_back_button': 'Go Back',
      'send_feedback_text': 'Please send us your feedback!',
      'enter_feedback_hint': 'Enter your feedback here...',
      'submit_feedback_button': 'Submit Feedback',
    },
    'es': {
      'thanks_feedback': '¡Gracias por tus comentarios!',
      'we_consider_text': 'Lo consideraremos cuidadosamente.',
      'go_back_button': 'Volver',
      'send_feedback_text': '¡Envíanos tus comentarios, por favor!',
      'enter_feedback_hint': 'Escribe tus comentarios aquí...',
      'submit_feedback_button': 'Enviar Comentarios',
    },
    'fr': {
      'thanks_feedback': 'Merci pour votre retour !',
      'we_consider_text': 'Nous l\'examinerons attentivement.',
      'go_back_button': 'Retour',
      'send_feedback_text': 'Veuillez nous envoyer vos commentaires !',
      'enter_feedback_hint': 'Entrez vos commentaires ici...',
      'submit_feedback_button': 'Soumettre les Commentaires',
    },
    'de': {
      'thanks_feedback': 'Danke für Ihr Feedback!',
      'we_consider_text': 'Wir werden es sorgfältig prüfen.',
      'go_back_button': 'Zurück',
      'send_feedback_text': 'Bitte senden Sie uns Ihr Feedback!',
      'enter_feedback_hint': 'Geben Sie Ihr Feedback hier ein...',
      'submit_feedback_button': 'Feedback Senden',
    },
    'it': {
      'thanks_feedback': 'Grazie per il tuo feedback!',
      'we_consider_text': 'Lo valuteremo attentamente.',
      'go_back_button': 'Torna Indietro',
      'send_feedback_text': 'Per favore inviaci il tuo feedback!',
      'enter_feedback_hint': 'Inserisci qui il tuo feedback...',
      'submit_feedback_button': 'Invia Feedback',
    },
    'pt': {
      'thanks_feedback': 'Obrigado pelo seu feedback!',
      'we_consider_text': 'Vamos considerá-lo com cuidado.',
      'go_back_button': 'Voltar',
      'send_feedback_text': 'Por favor, envie-nos o seu feedback!',
      'enter_feedback_hint': 'Digite seu feedback aqui...',
      'submit_feedback_button': 'Enviar Feedback',
    },
    'nl': {
      'thanks_feedback': 'Bedankt voor uw feedback!',
      'we_consider_text': 'We zullen het zorgvuldig overwegen.',
      'go_back_button': 'Ga Terug',
      'send_feedback_text': 'Stuur ons uw feedback!',
      'enter_feedback_hint': 'Voer hier uw feedback in...',
      'submit_feedback_button': 'Feedback Versturen',
    },
    'ru': {
      'thanks_feedback': 'Спасибо за ваш отзыв!',
      'we_consider_text': 'Мы тщательно его рассмотрим.',
      'go_back_button': 'Вернуться',
      'send_feedback_text': 'Пожалуйста, отправьте нам ваш отзыв!',
      'enter_feedback_hint': 'Введите ваш отзыв здесь...',
      'submit_feedback_button': 'Отправить Отзыв',
    },
    'zh': {
      'thanks_feedback': '感谢您的反馈！',
      'we_consider_text': '我们会认真考虑。',
      'go_back_button': '返回',
      'send_feedback_text': '请发送您的反馈！',
      'enter_feedback_hint': '在此处输入您的反馈...',
      'submit_feedback_button': '提交反馈',
    },
    'ja': {
      'thanks_feedback': 'ご意見ありがとうございます！',
      'we_consider_text': '慎重に検討します。',
      'go_back_button': '戻る',
      'send_feedback_text': 'フィードバックを送ってください！',
      'enter_feedback_hint': 'ここにフィードバックを入力してください...',
      'submit_feedback_button': 'フィードバックを送信',
    },
    'ko': {
      'thanks_feedback': '피드백 감사합니다!',
      'we_consider_text': '신중히 고려하겠습니다.',
      'go_back_button': '돌아가기',
      'send_feedback_text': '피드백을 보내주세요!',
      'enter_feedback_hint': '여기에 피드백을 입력하세요...',
      'submit_feedback_button': '피드백 제출',
    },
    'ar': {
      'thanks_feedback': 'شكرًا على ملاحظاتك!',
      'we_consider_text': 'سوف نأخذها بعين الاعتبار.',
      'go_back_button': 'عودة',
      'send_feedback_text': 'يرجى إرسال ملاحظاتك إلينا!',
      'enter_feedback_hint': 'أدخل ملاحظاتك هنا...',
      'submit_feedback_button': 'إرسال ملاحظات',
    },
    'hi': {
      'thanks_feedback': 'आपके फीडबैक के लिए धन्यवाद!',
      'we_consider_text': 'हम इसे ध्यान से विचार करेंगे।',
      'go_back_button': 'वापस जाएं',
      'send_feedback_text': 'कृपया हमें अपना फीडबैक भेजें!',
      'enter_feedback_hint': 'यहां अपना फीडबैक दर्ज करें...',
      'submit_feedback_button': 'फीडबैक सबमिट करें',
    },
    'tr': {
      'thanks_feedback': 'Geri bildiriminiz için teşekkür ederiz!',
      'we_consider_text': 'Bunu dikkatlice değerlendireceğiz.',
      'go_back_button': 'Geri Dön',
      'send_feedback_text': 'Lütfen bize geri bildiriminizi gönderin!',
      'enter_feedback_hint': 'Geri bildiriminizi buraya yazın...',
      'submit_feedback_button': 'Geri Bildirim Gönder',
    },
    'th': {
      'thanks_feedback': 'ขอบคุณสำหรับความคิดเห็นของคุณ!',
      'we_consider_text': 'เราจะพิจารณาอย่างรอบคอบ',
      'go_back_button': 'ย้อนกลับ',
      'send_feedback_text': 'กรุณาส่งความคิดเห็นของคุณให้เรา!',
      'enter_feedback_hint': 'กรอกความคิดเห็นของคุณที่นี่...',
      'submit_feedback_button': 'ส่งความคิดเห็น',
    },
    'sv': {
      'thanks_feedback': 'Tack för din feedback!',
      'we_consider_text': 'Vi kommer att överväga det noggrant.',
      'go_back_button': 'Gå Tillbaka',
      'send_feedback_text': 'Vänligen skicka oss din feedback!',
      'enter_feedback_hint': 'Skriv din feedback här...',
      'submit_feedback_button': 'Skicka Feedback',
    },
    'el': {
      'thanks_feedback': 'Ευχαριστούμε για τα σχόλιά σας!',
      'we_consider_text': 'Θα το εξετάσουμε προσεκτικά.',
      'go_back_button': 'Επιστροφή',
      'send_feedback_text': 'Στείλτε μας τα σχόλιά σας, παρακαλώ!',
      'enter_feedback_hint': 'Εισαγάγετε τα σχόλιά σας εδώ...',
      'submit_feedback_button': 'Υποβολή Σχολίων',
    },
    'pl': {
      'thanks_feedback': 'Dziękujemy za twoją opinię!',
      'we_consider_text': 'Starannie to rozważymy.',
      'go_back_button': 'Wróć',
      'send_feedback_text': 'Prosimy o przesłanie swojej opinii!',
      'enter_feedback_hint': 'Wpisz swoją opinię tutaj...',
      'submit_feedback_button': 'Prześlij Opinię',
    },
    'vi': {
      'thanks_feedback': 'Cảm ơn bạn đã góp ý!',
      'we_consider_text': 'Chúng tôi sẽ xem xét cẩn thận.',
      'go_back_button': 'Quay Lại',
      'send_feedback_text': 'Hãy gửi ý kiến phản hồi của bạn cho chúng tôi!',
      'enter_feedback_hint': 'Nhập ý kiến phản hồi tại đây...',
      'submit_feedback_button': 'Gửi Phản Hồi',
    },
  };
  static String getFeedbackLabel(String langCode, String key) {
    return feedbackStrings[langCode]?[key] ?? key;
  }

}