class DonationLabels {
  static Map<String, Map<String, String>> labels = {
    // English (en)
    'en': {
      'leaderboard_value': 'Leaderboard',
      'donate_now_value': 'Donate Now',
      'make_a_donation_value': 'Make a Donation',
      'custom_amount_hint_value': 'Enter Custom Amount',
      'donation_category_hint_value': 'Donation Category',
      'description_hint_value': 'Description (Optional)',
      'payment_method_hint_value': 'Payment Method',
      'cancel_button': 'Cancel',
      'donate_button': 'Donate',
      'required_fields_err_value': 'Please fill all required fields.',
      'add_card_button': 'Add Card',
      'no_payment_method_title_value': 'No Payment Methods',
      'no_payment_method_description_value': 'You have no payment methods saved. Please add a card to proceed with a donation.',
      'goal_achieved_expired_carousel_value': '🎉 Goal Achieved!',
      'inactive_expired_carousel_value': 'Inactive',
      'amount_not_raised_expired_carousel_value': 'Amount Not Raised',
      'timer_days_value': 'days',
      'no_internet_connection': 'No Internet Connection',
      'no_donation_items': 'No donation items available.',
      'first_to_add_score': 'Be the first to add a score!',
      'no_data_available': 'No data available',
      'custom_amount_label_value': 'Custom Amount'
    },
    // Spanish (es)
    'es': {
      'leaderboard_value': 'Clasificación',
      'donate_now_value': 'Donar Ahora',
      'make_a_donation_value': 'Realizar una Donación',
      'custom_amount_hint_value': 'Ingrese Monto Personalizado',
      'donation_category_hint_value': 'Categoría de Donación',
      'description_hint_value': 'Descripción (Opcional)',
      'payment_method_hint_value': 'Método de Pago',
      'cancel_button': 'Cancelar',
      'donate_button': 'Donar',
      'required_fields_err_value': 'Por favor complete todos los campos obligatorios.',
      'add_card_button': 'Agregar Tarjeta',
      'no_payment_method_title_value': 'Sin Métodos de Pago',
      'no_payment_method_description_value': 'No tienes métodos de pago guardados. Agrega una tarjeta para proceder con una donación.',
      'goal_achieved_expired_carousel_value': '🎉 ¡Meta Alcanzada!',
      'inactive_expired_carousel_value': 'Inactivo',
      'amount_not_raised_expired_carousel_value': 'Cantidad No Recaudada',
      'timer_days_value': 'días',
      'no_internet_connection': 'Sin conexión a Internet',
      'no_donation_items': 'No hay artículos de donación disponibles.',
      'first_to_add_score': '¡Sé el primero en agregar una puntuación!',
      'no_data_available': 'No hay datos disponibles',
      'custom_amount_label_value': 'Cantidad Personalizada'
    },
    // French (fr)
    'fr': {
      'leaderboard_value': 'Classement',
      'donate_now_value': 'Faire un Don',
      'make_a_donation_value': 'Faire une Donation',
      'custom_amount_hint_value': 'Entrez un Montant Personnalisé',
      'donation_category_hint_value': 'Catégorie de Don',
      'description_hint_value': 'Description (Optionnelle)',
      'payment_method_hint_value': 'Méthode de Paiement',
      'cancel_button': 'Annuler',
      'donate_button': 'Donner',
      'required_fields_err_value': 'Veuillez remplir tous les champs obligatoires.',
      'add_card_button': 'Ajouter une Carte',
      'no_payment_method_title_value': 'Aucune Méthode de Paiement',
      'no_payment_method_description_value': 'Vous n’avez aucune méthode de paiement enregistrée. Veuillez ajouter une carte pour procéder à un don.',
      'goal_achieved_expired_carousel_value': '🎉 Objectif Atteint!',
      'inactive_expired_carousel_value': 'Inactif',
      'amount_not_raised_expired_carousel_value': 'Montant Non Collecté',
      'timer_days_value': 'jours',
      'no_internet_connection': 'Pas de connexion Internet',
      'no_donation_items': 'Aucun article de don disponible.',
      'first_to_add_score': 'Soyez le premier à ajouter un score!',
      'no_data_available': 'Aucune donnée disponible',
      'custom_amount_label_value': 'Montant Personnalisé'
    },
    // German (de)
    'de': {
      'leaderboard_value': 'Rangliste',
      'donate_now_value': 'Jetzt Spenden',
      'make_a_donation_value': 'Eine Spende Tätigen',
      'custom_amount_hint_value': 'Betrag Eingeben',
      'donation_category_hint_value': 'Spendenkategorie',
      'description_hint_value': 'Beschreibung (Optional)',
      'payment_method_hint_value': 'Zahlungsmethode',
      'cancel_button': 'Abbrechen',
      'donate_button': 'Spenden',
      'required_fields_err_value': 'Bitte füllen Sie alle erforderlichen Felder aus.',
      'add_card_button': 'Karte Hinzufügen',
      'no_payment_method_title_value': 'Keine Zahlungsmethoden',
      'no_payment_method_description_value': 'Sie haben keine Zahlungsmethoden gespeichert. Bitte fügen Sie eine Karte hinzu, um mit einer Spende fortzufahren.',
      'goal_achieved_expired_carousel_value': '🎉 Ziel Erreicht!',
      'inactive_expired_carousel_value': 'Inaktiv',
      'amount_not_raised_expired_carousel_value': 'Betrag Nicht Erreicht',
      'timer_days_value': 'Tage',
      'no_internet_connection': 'Keine Internetverbindung',
      'no_donation_items': 'Keine Spendenartikel verfügbar.',
      'first_to_add_score': 'Sei der Erste, der einen Punkt hinzufügt!',
      'no_data_available': 'Keine Daten verfügbar',
      'custom_amount_label_value': 'Benutzerdefinierter Betrag'
    },
    // Italian (it)
    'it': {
      'leaderboard_value': 'Classifica',
      'donate_now_value': 'Dona Ora',
      'make_a_donation_value': 'Fai una Donazione',
      'custom_amount_hint_value': 'Inserisci Importo Personalizzato',
      'donation_category_hint_value': 'Categoria di Donazione',
      'description_hint_value': 'Descrizione (Opzionale)',
      'payment_method_hint_value': 'Metodo di Pagamento',
      'cancel_button': 'Annulla',
      'donate_button': 'Dona',
      'required_fields_err_value': 'Compila tutti i campi obbligatori.',
      'add_card_button': 'Aggiungi Carta',
      'no_payment_method_title_value': 'Nessun Metodo di Pagamento',
      'no_payment_method_description_value': 'Non hai metodi di pagamento salvati. Aggiungi una carta per procedere con una donazione.',
      'goal_achieved_expired_carousel_value': '🎉 Obiettivo Raggiunto!',
      'inactive_expired_carousel_value': 'Inattivo',
      'amount_not_raised_expired_carousel_value': 'Importo Non Raccolto',
      'timer_days_value': 'giorni',
      'no_internet_connection': 'Nessuna connessione Internet',
      'no_donation_items': 'Nessun articolo di donazione disponibile.',
      'first_to_add_score': 'Sii il primo ad aggiungere un punteggio!',
      'no_data_available': 'Nessun dato disponibile',
      'custom_amount_label_value': 'Importo Personalizzato'
    },
    // Portuguese (pt)
    'pt': {
      'leaderboard_value': 'Classificação',
      'donate_now_value': 'Doe Agora',
      'make_a_donation_value': 'Fazer uma Doação',
      'custom_amount_hint_value': 'Insira o Valor Personalizado',
      'donation_category_hint_value': 'Categoria de Doação',
      'description_hint_value': 'Descrição (Opcional)',
      'payment_method_hint_value': 'Método de Pagamento',
      'cancel_button': 'Cancelar',
      'donate_button': 'Doar',
      'required_fields_err_value': 'Por favor, preencha todos os campos obrigatórios.',
      'add_card_button': 'Adicionar Cartão',
      'no_payment_method_title_value': 'Sem Métodos de Pagamento',
      'no_payment_method_description_value': 'Você não tem métodos de pagamento salvos. Adicione um cartão para continuar com a doação.',
      'goal_achieved_expired_carousel_value': '🎉 Objetivo Alcançado!',
      'inactive_expired_carousel_value': 'Inativo',
      'amount_not_raised_expired_carousel_value': 'Valor Não Arrecadado',
      'timer_days_value': 'dias',
      'no_internet_connection': 'Sem Conexão com a Internet',
      'no_donation_items': 'Nenhum item de doação disponível.',
      'first_to_add_score': 'Seja o primeiro a adicionar uma pontuação!',
      'no_data_available': 'Nenhum dado disponível',
      'custom_amount_label_value': 'Valor Personalizado'
    },
    // Dutch (nl)
    'nl': {
      'leaderboard_value': 'Leaderboard',
      'donate_now_value': 'Doneer Nu',
      'make_a_donation_value': 'Doe een Donatie',
      'custom_amount_hint_value': 'Voer een Aangepast Bedrag in',
      'donation_category_hint_value': 'Donatiecategorie',
      'description_hint_value': 'Beschrijving (Optioneel)',
      'payment_method_hint_value': 'Betalmethode',
      'cancel_button': 'Annuleren',
      'donate_button': 'Doneer',
      'required_fields_err_value': 'Vul alle verplichte velden in.',
      'add_card_button': 'Voeg Kaart Toe',
      'no_payment_method_title_value': 'Geen Betalingsmethoden',
      'no_payment_method_description_value': 'Je hebt geen betalingsmethoden opgeslagen. Voeg een kaart toe om door te gaan met doneren.',
      'goal_achieved_expired_carousel_value': '🎉 Doel Bereikt!',
      'inactive_expired_carousel_value': 'Inactief',
      'amount_not_raised_expired_carousel_value': 'Bedrag Niet Verzameld',
      'timer_days_value': 'dagen',
      'no_internet_connection': 'Geen Internetverbinding',
      'no_donation_items': 'Geen donatie-items beschikbaar.',
      'first_to_add_score': 'Wees de eerste om een score toe te voegen!',
      'no_data_available': 'Geen gegevens beschikbaar',
      'custom_amount_label_value': 'Aangepast Bedrag'
    },
    // Russian (ru)
    'ru': {
      'leaderboard_value': 'Таблица лидеров',
      'donate_now_value': 'Пожертвовать Сейчас',
      'make_a_donation_value': 'Сделать Пожертвование',
      'custom_amount_hint_value': 'Введите Сумму',
      'donation_category_hint_value': 'Категория Пожертвования',
      'description_hint_value': 'Описание (Необязательно)',
      'payment_method_hint_value': 'Способ Оплаты',
      'cancel_button': 'Отмена',
      'donate_button': 'Пожертвовать',
      'required_fields_err_value': 'Пожалуйста, заполните все обязательные поля.',
      'add_card_button': 'Добавить Карточку',
      'no_payment_method_title_value': 'Нет Способов Оплаты',
      'no_payment_method_description_value': 'У вас нет сохраненных способов оплаты. Пожалуйста, добавьте карту, чтобы продолжить пожертвование.',
      'goal_achieved_expired_carousel_value': '🎉 Цель Достигнута!',
      'inactive_expired_carousel_value': 'Неактивно',
      'amount_not_raised_expired_carousel_value': 'Сумма Не Собрана',
      'timer_days_value': 'дни',
      'no_internet_connection': 'Нет Подключения к Интернету',
      'no_donation_items': 'Нет доступных предметов для пожертвования.',
      'first_to_add_score': 'Будьте первыми, кто добавит баллы!',
      'no_data_available': 'Нет доступных данных',
      'custom_amount_label_value': 'Сумма на заказ'
    },
    // Chinese (zh)
    'zh': {
      'leaderboard_value': '排行榜',
      'donate_now_value': '立即捐赠',
      'make_a_donation_value': '进行捐赠',
      'custom_amount_hint_value': '输入自定义金额',
      'donation_category_hint_value': '捐赠类别',
      'description_hint_value': '描述（可选）',
      'payment_method_hint_value': '支付方式',
      'cancel_button': '取消',
      'donate_button': '捐赠',
      'required_fields_err_value': '请填写所有必填字段。',
      'add_card_button': '添加卡片',
      'no_payment_method_title_value': '没有支付方式',
      'no_payment_method_description_value': '您没有保存支付方式。请添加卡片继续捐赠。',
      'goal_achieved_expired_carousel_value': '🎉 达成目标！',
      'inactive_expired_carousel_value': '不活跃',
      'amount_not_raised_expired_carousel_value': '金额未筹集',
      'timer_days_value': '天',
      'no_internet_connection': '没有互联网连接',
      'no_donation_items': '没有捐赠项目',
      'first_to_add_score': '成为第一个添加分数的人！',
      'no_data_available': '没有数据可用',
      'custom_amount_label_value': '自定义金额'
    },
    // Japanese (ja)
    'ja': {
      'leaderboard_value': 'リーダーボード',
      'donate_now_value': '今すぐ寄付',
      'make_a_donation_value': '寄付する',
      'custom_amount_hint_value': 'カスタム金額を入力',
      'donation_category_hint_value': '寄付カテゴリ',
      'description_hint_value': '説明（オプション）',
      'payment_method_hint_value': '支払い方法',
      'cancel_button': 'キャンセル',
      'donate_button': '寄付する',
      'required_fields_err_value': '必須項目をすべて記入してください。',
      'add_card_button': 'カードを追加',
      'no_payment_method_title_value': '支払い方法なし',
      'no_payment_method_description_value': '保存された支払い方法がありません。寄付を続けるにはカードを追加してください。',
      'goal_achieved_expired_carousel_value': '🎉 目標達成！',
      'inactive_expired_carousel_value': '非アクティブ',
      'amount_not_raised_expired_carousel_value': '金額が集められていません',
      'timer_days_value': '日',
      'no_internet_connection': 'インターネット接続なし',
      'no_donation_items': '寄付項目はありません',
      'first_to_add_score': '最初にスコアを追加するのはあなたです！',
      'no_data_available': 'データは利用できません',
      'custom_amount_label_value': 'カスタム金額'
    },
    // Korean (ko)
    'ko': {
      'leaderboard_value': '리더보드',
      'donate_now_value': '지금 기부하기',
      'make_a_donation_value': '기부하기',
      'custom_amount_hint_value': '맞춤 금액 입력',
      'donation_category_hint_value': '기부 카테고리',
      'description_hint_value': '설명 (선택사항)',
      'payment_method_hint_value': '지불 방법',
      'cancel_button': '취소',
      'donate_button': '기부하기',
      'required_fields_err_value': '모든 필수 필드를 작성해 주세요.',
      'add_card_button': '카드 추가',
      'no_payment_method_title_value': '지불 방법 없음',
      'no_payment_method_description_value': '저장된 지불 방법이 없습니다. 기부를 진행하려면 카드를 추가하십시오.',
      'goal_achieved_expired_carousel_value': '🎉 목표 달성!',
      'inactive_expired_carousel_value': '비활성',
      'amount_not_raised_expired_carousel_value': '모금액 미달성',
      'timer_days_value': '일',
      'no_internet_connection': '인터넷 연결 없음',
      'no_donation_items': '기부 항목 없음',
      'first_to_add_score': '가장 먼저 점수를 추가하세요!',
      'no_data_available': '사용 가능한 데이터 없음',
      'custom_amount_label_value': '맞춤 금액'
    },
    // Arabic (ar)
    'ar': {
      'leaderboard_value': 'لوحة الصدارة',
      'donate_now_value': 'تبرع الآن',
      'make_a_donation_value': 'قم بالتبرع',
      'custom_amount_hint_value': 'أدخل المبلغ المخصص',
      'donation_category_hint_value': 'فئة التبرع',
      'description_hint_value': 'الوصف (اختياري)',
      'payment_method_hint_value': 'طريقة الدفع',
      'cancel_button': 'إلغاء',
      'donate_button': 'تبرع',
      'required_fields_err_value': 'يرجى ملء جميع الحقول المطلوبة.',
      'add_card_button': 'إضافة بطاقة',
      'no_payment_method_title_value': 'لا توجد طرق دفع',
      'no_payment_method_description_value': 'لا توجد طرق دفع محفوظة. يرجى إضافة بطاقة للمتابعة بالتبرع.',
      'goal_achieved_expired_carousel_value': '🎉 تم تحقيق الهدف!',
      'inactive_expired_carousel_value': 'غير نشط',
      'amount_not_raised_expired_carousel_value': 'المبلغ غير مجمع',
      'timer_days_value': 'أيام',
      'no_internet_connection': 'لا يوجد اتصال بالإنترنت',
      'no_donation_items': 'لا توجد عناصر تبرع متاحة.',
      'first_to_add_score': 'كن أول من يضيف النقاط!',
      'no_data_available': 'لا توجد بيانات متاحة',
      'custom_amount_label_value': 'مبلغ مخصص'
    },
    // Hindi (hi)
    'hi': {
      'leaderboard_value': 'लीडरबोर्ड',
      'donate_now_value': 'अब दान करें',
      'make_a_donation_value': 'दान करें',
      'custom_amount_hint_value': 'कस्टम राशि दर्ज करें',
      'donation_category_hint_value': 'दान श्रेणी',
      'description_hint_value': 'विवरण (वैकल्पिक)',
      'payment_method_hint_value': 'भुगतान विधि',
      'cancel_button': 'रद्द करें',
      'donate_button': 'दान करें',
      'required_fields_err_value': 'कृपया सभी आवश्यक क्षेत्रों को भरें।',
      'add_card_button': 'कार्ड जोड़ें',
      'no_payment_method_title_value': 'कोई भुगतान विधियाँ नहीं हैं',
      'no_payment_method_description_value': 'आपके पास कोई भुगतान विधियाँ नहीं हैं। कृपया दान करने के लिए एक कार्ड जोड़ें।',
      'goal_achieved_expired_carousel_value': '🎉 लक्ष्य प्राप्त!',
      'inactive_expired_carousel_value': 'निष्क्रिय',
      'amount_not_raised_expired_carousel_value': 'राशि एकत्रित नहीं की गई',
      'timer_days_value': 'दिन',
      'no_internet_connection': 'कोई इंटरनेट कनेक्शन नहीं',
      'no_donation_items': 'कोई दान आइटम उपलब्ध नहीं हैं',
      'first_to_add_score': 'स्कोर जोड़ने वाला पहला बनें!',
      'no_data_available': 'कोई डेटा उपलब्ध नहीं है',
      'custom_amount_label_value': 'कस्टम राशि'
    },
    // Turkish (tr)
    'tr': {
      'leaderboard_value': 'Liderlik Tablosu',
      'donate_now_value': 'Hemen Bağış Yap',
      'make_a_donation_value': 'Bağış Yap',
      'custom_amount_hint_value': 'Özel Miktar Girin',
      'donation_category_hint_value': 'Bağış Kategorisi',
      'description_hint_value': 'Açıklama (Opsiyonel)',
      'payment_method_hint_value': 'Ödeme Yöntemi',
      'cancel_button': 'İptal',
      'donate_button': 'Bağış Yap',
      'required_fields_err_value': 'Lütfen tüm zorunlu alanları doldurun.',
      'add_card_button': 'Kart Ekle',
      'no_payment_method_title_value': 'Ödeme Yöntemi Yok',
      'no_payment_method_description_value': 'Kaydedilmiş ödeme yönteminiz yok. Bağış yapmaya devam etmek için bir kart ekleyin.',
      'goal_achieved_expired_carousel_value': '🎉 Hedef Gerçekleşti!',
      'inactive_expired_carousel_value': 'Pasif',
      'amount_not_raised_expired_carousel_value': 'Toplanan Miktar Yok',
      'timer_days_value': 'gün',
      'no_internet_connection': 'İnternet Bağlantısı Yok',
      'no_donation_items': 'Bağış için öğe yok.',
      'first_to_add_score': 'İlk puanı ekleyen siz olun!',
      'no_data_available': 'Veri mevcut değil',
      'custom_amount_label_value': 'Özel Tutar'
    },
    // Thai (th)
    'th': {
      'leaderboard_value': 'กระดานผู้นำ',
      'donate_now_value': 'บริจาคเดี๋ยวนี้',
      'make_a_donation_value': 'ทำการบริจาค',
      'custom_amount_hint_value': 'กรอกจำนวนที่กำหนดเอง',
      'donation_category_hint_value': 'หมวดหมู่การบริจาค',
      'description_hint_value': 'คำอธิบาย (ถ้ามี)',
      'payment_method_hint_value': 'วิธีการชำระเงิน',
      'cancel_button': 'ยกเลิก',
      'donate_button': 'บริจาค',
      'required_fields_err_value': 'กรุณากรอกข้อมูลให้ครบทุกช่อง',
      'add_card_button': 'เพิ่มบัตร',
      'no_payment_method_title_value': 'ไม่มีวิธีการชำระเงิน',
      'no_payment_method_description_value': 'คุณไม่มีวิธีการชำระเงินที่บันทึกไว้ กรุณาเพิ่มบัตรเพื่อดำเนินการบริจาค',
      'goal_achieved_expired_carousel_value': '🎉 เป้าหมายสำเร็จ!',
      'inactive_expired_carousel_value': 'ไม่เปิดใช้งาน',
      'amount_not_raised_expired_carousel_value': 'ยอดที่ยังไม่ถึง',
      'timer_days_value': 'วัน',
      'no_internet_connection': 'ไม่มีการเชื่อมต่ออินเทอร์เน็ต',
      'no_donation_items': 'ไม่มีรายการบริจาค',
      'first_to_add_score': 'เป็นคนแรกที่เพิ่มคะแนน!',
      'no_data_available': 'ไม่มีข้อมูล',
      'custom_amount_label_value': 'จำนวนเงินที่กำหนดเอง'
    },
    // Swedish (sv)
    'sv': {
      'leaderboard_value': 'Leaderboard',
      'donate_now_value': 'Donera Nu',
      'make_a_donation_value': 'Gör en Donation',
      'custom_amount_hint_value': 'Ange Anpassat Belopp',
      'donation_category_hint_value': 'Donationskategori',
      'description_hint_value': 'Beskrivning (Valfritt)',
      'payment_method_hint_value': 'Betalningsmetod',
      'cancel_button': 'Avbryt',
      'donate_button': 'Donera',
      'required_fields_err_value': 'Vänligen fyll i alla obligatoriska fält.',
      'add_card_button': 'Lägg till Kort',
      'no_payment_method_title_value': 'Inga Betalningsmetoder',
      'no_payment_method_description_value': 'Du har inga betalningsmetoder sparade. Lägg till ett kort för att fortsätta med donationen.',
      'goal_achieved_expired_carousel_value': '🎉 Mål Uppnått!',
      'inactive_expired_carousel_value': 'Inaktiv',
      'amount_not_raised_expired_carousel_value': 'Belopp Ej Insamlat',
      'timer_days_value': 'dagar',
      'no_internet_connection': 'Ingen Internetanslutning',
      'no_donation_items': 'Inga donationsobjekt tillgängliga.',
      'first_to_add_score': 'Var den första att lägga till poäng!',
      'no_data_available': 'Ingen data tillgänglig',
      'custom_amount_label_value': 'Anpassat Belopp'
    },
    // Greek (el)
    'el': {
      'leaderboard_value': 'Πίνακας Κατάταξης',
      'donate_now_value': 'Δωρεά Τώρα',
      'make_a_donation_value': 'Κάντε Μια Δωρεά',
      'custom_amount_hint_value': 'Εισάγετε Προσαρμοσμένο Ποσό',
      'donation_category_hint_value': 'Κατηγορία Δωρεάς',
      'description_hint_value': 'Περιγραφή (Προαιρετικό)',
      'payment_method_hint_value': 'Μέθοδος Πληρωμής',
      'cancel_button': 'Ακύρωση',
      'donate_button': 'Δωρεά',
      'required_fields_err_value': 'Παρακαλώ συμπληρώστε όλα τα απαιτούμενα πεδία.',
      'add_card_button': 'Προσθήκη Κάρτας',
      'no_payment_method_title_value': 'Χωρίς Μεθόδους Πληρωμής',
      'no_payment_method_description_value': 'Δεν έχετε αποθηκευμένες μεθόδους πληρωμής. Προσθέστε μια κάρτα για να συνεχίσετε με τη δωρεά.',
      'goal_achieved_expired_carousel_value': '🎉 Στόχος Επιτεύχθηκε!',
      'inactive_expired_carousel_value': 'Αδρανές',
      'amount_not_raised_expired_carousel_value': 'Ποσό Δεν Συλλέχθηκε',
      'timer_days_value': 'ημέρες',
      'no_internet_connection': 'Χωρίς Σύνδεση στο Διαδίκτυο',
      'no_donation_items': 'Δεν υπάρχουν διαθέσιμα αντικείμενα δωρεάς.',
      'first_to_add_score': 'Γίνε ο πρώτος που προσθέτει σκορ!',
      'no_data_available': 'Δεν υπάρχουν διαθέσιμα δεδομένα',
      'custom_amount_label_value': 'Προσαρμοσμένο Ποσό'
    },
    // Polish (pl)
    'pl': {
      'leaderboard_value': 'Tablica Liderów',
      'donate_now_value': 'Przekaż Darowiznę',
      'make_a_donation_value': 'Zrób Darowiznę',
      'custom_amount_hint_value': 'Wprowadź Własną Kwotę',
      'donation_category_hint_value': 'Kategoria Darowizny',
      'description_hint_value': 'Opis (Opcjonalnie)',
      'payment_method_hint_value': 'Metoda Płatności',
      'cancel_button': 'Anuluj',
      'donate_button': 'Przekaż Darowiznę',
      'required_fields_err_value': 'Proszę wypełnić wszystkie wymagane pola.',
      'add_card_button': 'Dodaj Kartę',
      'no_payment_method_title_value': 'Brak Metod Płatności',
      'no_payment_method_description_value': 'Nie masz zapisanych metod płatności. Proszę dodać kartę, aby kontynuować darowiznę.',
      'goal_achieved_expired_carousel_value': '🎉 Cel Osiągnięty!',
      'inactive_expired_carousel_value': 'Nieaktywny',
      'amount_not_raised_expired_carousel_value': 'Kwota Nie Zebrana',
      'timer_days_value': 'dni',
      'no_internet_connection': 'Brak Połączenia z Internetem',
      'no_donation_items': 'Brak dostępnych przedmiotów do darowizny.',
      'first_to_add_score': 'Bądź pierwszym, który doda wynik!',
      'no_data_available': 'Brak dostępnych danych',
      'custom_amount_label_value': 'Kwota Niestandardowa'
    },
    // Vietnamese (vi)
    'vi': {
      'leaderboard_value': 'Bảng xếp hạng',
      'donate_now_value': 'Đóng góp ngay',
      'make_a_donation_value': 'Thực hiện đóng góp',
      'custom_amount_hint_value': 'Nhập số tiền tùy chỉnh',
      'donation_category_hint_value': 'Danh mục đóng góp',
      'description_hint_value': 'Mô tả (Tùy chọn)',
      'payment_method_hint_value': 'Phương thức thanh toán',
      'cancel_button': 'Hủy',
      'donate_button': 'Đóng góp',
      'required_fields_err_value': 'Vui lòng điền tất cả các trường bắt buộc.',
      'add_card_button': 'Thêm thẻ',
      'no_payment_method_title_value': 'Không có phương thức thanh toán',
      'no_payment_method_description_value': 'Bạn chưa lưu phương thức thanh toán. Vui lòng thêm thẻ để tiếp tục đóng góp.',
      'goal_achieved_expired_carousel_value': '🎉 Mục tiêu đạt được!',
      'inactive_expired_carousel_value': 'Không hoạt động',
      'amount_not_raised_expired_carousel_value': 'Số tiền chưa được thu',
      'timer_days_value': 'ngày',
      'no_internet_connection': 'Không có kết nối Internet',
      'no_donation_items': 'Không có món quà đóng góp',
      'first_to_add_score': 'Hãy là người đầu tiên thêm điểm!',
      'no_data_available': 'Không có dữ liệu',
      'custom_amount_label_value': 'Số Tiền Tùy Chỉnh'
    }
  };

  static String getLabel(String langCode, String key) {
    return labels[langCode]?[key] ?? key;
  }
}
