class DonationLabels {
  static Map<String, Map<String, String>> labels = {
    // English (en)
    'en': {
      'leaderboard_value': 'Leaderboard',
      'donate_now_value': 'Donate Now',
      'make_a_donation_value': 'Make a Donation',
      'custom_amount_hint_value': 'Enter Custom Amount',
      'donation_category_hint_value': 'Donation Category',
      'description_hint_value': 'Description (Optional)',
      'payment_method_hint_value': 'Payment Method',
      'cancel_button': 'Cancel',
      'donate_button': 'Donate',
      'required_fields_err_value': 'Please fill all required fields.',
      'add_card_button': 'Add Card',
      'no_payment_method_title_value': 'No Payment Methods',
      'no_payment_method_description_value': 'You have no payment methods saved. Please add a card to proceed with a donation.',
      'goal_achieved_expired_carousel_value': '🎉 Goal Achieved!',
      'inactive_expired_carousel_value': 'Inactive',
      'amount_not_raised_expired_carousel_value': 'Amount Not Raised',
      'timer_days_value': 'days',
    },
    // Spanish (es)
    'es': {
      'leaderboard_value': 'Clasificación',
      'donate_now_value': 'Donar Ahora',
      'make_a_donation_value': 'Realizar una Donación',
      'custom_amount_hint_value': 'Ingrese Monto Personalizado',
      'donation_category_hint_value': 'Categoría de Donación',
      'description_hint_value': 'Descripción (Opcional)',
      'payment_method_hint_value': 'Método de Pago',
      'cancel_button': 'Cancelar',
      'donate_button': 'Donar',
      'required_fields_err_value': 'Por favor complete todos los campos obligatorios.',
      'add_card_button': 'Agregar Tarjeta',
      'no_payment_method_title_value': 'Sin Métodos de Pago',
      'no_payment_method_description_value': 'No tienes métodos de pago guardados. Agrega una tarjeta para proceder con una donación.',
      'goal_achieved_expired_carousel_value': '🎉 ¡Meta Alcanzada!',
      'inactive_expired_carousel_value': 'Inactivo',
      'amount_not_raised_expired_carousel_value': 'Cantidad No Recaudada',
      'timer_days_value': 'días',
    },
    // French (fr)
    'fr': {
      'leaderboard_value': 'Classement',
      'donate_now_value': 'Faire un Don',
      'make_a_donation_value': 'Faire une Donation',
      'custom_amount_hint_value': 'Entrez un Montant Personnalisé',
      'donation_category_hint_value': 'Catégorie de Don',
      'description_hint_value': 'Description (Optionnelle)',
      'payment_method_hint_value': 'Méthode de Paiement',
      'cancel_button': 'Annuler',
      'donate_button': 'Donner',
      'required_fields_err_value': 'Veuillez remplir tous les champs obligatoires.',
      'add_card_button': 'Ajouter une Carte',
      'no_payment_method_title_value': 'Aucune Méthode de Paiement',
      'no_payment_method_description_value': 'Vous n’avez aucune méthode de paiement enregistrée. Veuillez ajouter une carte pour procéder à un don.',
      'goal_achieved_expired_carousel_value': '🎉 Objectif Atteint!',
      'inactive_expired_carousel_value': 'Inactif',
      'amount_not_raised_expired_carousel_value': 'Montant Non Collecté',
      'timer_days_value': 'jours',
    },
    // German (de)
    'de': {
      'leaderboard_value': 'Bestenliste',
      'donate_now_value': 'Jetzt Spenden',
      'make_a_donation_value': 'Spende Tätigen',
      'custom_amount_hint_value': 'Geben Sie einen individuellen Betrag ein',
      'donation_category_hint_value': 'Spendenkategorie',
      'description_hint_value': 'Beschreibung (Optional)',
      'payment_method_hint_value': 'Zahlungsmethode',
      'cancel_button': 'Abbrechen',
      'donate_button': 'Spenden',
      'required_fields_err_value': 'Bitte füllen Sie alle Pflichtfelder aus.',
      'add_card_button': 'Karte Hinzufügen',
      'no_payment_method_title_value': 'Keine Zahlungsmethoden',
      'no_payment_method_description_value': 'Sie haben keine Zahlungsmethoden gespeichert. Bitte fügen Sie eine Karte hinzu, um mit einer Spende fortzufahren.',
      'goal_achieved_expired_carousel_value': '🎉 Ziel Erreicht!',
      'inactive_expired_carousel_value': 'Inaktiv',
      'amount_not_raised_expired_carousel_value': 'Betrag Nicht Erreicht',
      'timer_days_value': 'Tage',
    },
    // Italian (it)
    'it': {
      'leaderboard_value': 'Classifica',
      'donate_now_value': 'Dona Ora',
      'make_a_donation_value': 'Fai una Donazione',
      'custom_amount_hint_value': 'Inserisci un Importo Personalizzato',
      'donation_category_hint_value': 'Categoria di Donazione',
      'description_hint_value': 'Descrizione (Opzionale)',
      'payment_method_hint_value': 'Metodo di Pagamento',
      'cancel_button': 'Annulla',
      'donate_button': 'Dona',
      'required_fields_err_value': 'Per favore, compila tutti i campi obbligatori.',
      'add_card_button': 'Aggiungi Carta',
      'no_payment_method_title_value': 'Nessun Metodo di Pagamento',
      'no_payment_method_description_value': 'Non hai metodi di pagamento salvati. Aggiungi una carta per procedere con la donazione.',
      'goal_achieved_expired_carousel_value': '🎉 Obiettivo Raggiunto!',
      'inactive_expired_carousel_value': 'Inattivo',
      'amount_not_raised_expired_carousel_value': 'Importo Non Raggiunto',
      'timer_days_value': 'giorni',
    },
    // Portuguese (pt)
    'pt': {
      'leaderboard_value': 'Classificação',
      'donate_now_value': 'Doe Agora',
      'make_a_donation_value': 'Faça uma Doação',
      'custom_amount_hint_value': 'Digite um Valor Personalizado',
      'donation_category_hint_value': 'Categoria de Doação',
      'description_hint_value': 'Descrição (Opcional)',
      'payment_method_hint_value': 'Método de Pagamento',
      'cancel_button': 'Cancelar',
      'donate_button': 'Doar',
      'required_fields_err_value': 'Por favor, preencha todos os campos obrigatórios.',
      'add_card_button': 'Adicionar Cartão',
      'no_payment_method_title_value': 'Sem Métodos de Pagamento',
      'no_payment_method_description_value': 'Você não tem métodos de pagamento salvos. Por favor, adicione um cartão para proceder com uma doação.',
      'goal_achieved_expired_carousel_value': '🎉 Meta Alcançada!',
      'inactive_expired_carousel_value': 'Inativo',
      'amount_not_raised_expired_carousel_value': 'Valor Não Arrecadado',
      'timer_days_value': 'dias',
    },
    // Dutch (nl)
    'nl': {
      'leaderboard_value': 'Ranglijst',
      'donate_now_value': 'Doneer Nu',
      'make_a_donation_value': 'Doe een Donatie',
      'custom_amount_hint_value': 'Voer een Aangepast Bedrag in',
      'donation_category_hint_value': 'Donatiecategorie',
      'description_hint_value': 'Beschrijving (Optioneel)',
      'payment_method_hint_value': 'Betaalmethode',
      'cancel_button': 'Annuleren',
      'donate_button': 'Doneer',
      'required_fields_err_value': 'Vul alle verplichte velden in.',
      'add_card_button': 'Voeg Kaart Toe',
      'no_payment_method_title_value': 'Geen Betaalmethoden',
      'no_payment_method_description_value': 'U heeft geen betaalmethoden opgeslagen. Voeg een kaart toe om door te gaan met een donatie.',
      'goal_achieved_expired_carousel_value': '🎉 Doel Behaald!',
      'inactive_expired_carousel_value': 'Inactief',
      'amount_not_raised_expired_carousel_value': 'Bedrag Niet Behaald',
      'timer_days_value': 'dagen',
    },
    // Russian (ru)
    'ru': {
      'leaderboard_value': 'Лидерборд',
      'donate_now_value': 'Пожертвовать Сейчас',
      'make_a_donation_value': 'Сделать Пожертвование',
      'custom_amount_hint_value': 'Введите произвольную сумму',
      'donation_category_hint_value': 'Категория Пожертвования',
      'description_hint_value': 'Описание (Необязательно)',
      'payment_method_hint_value': 'Способ оплаты',
      'cancel_button': 'Отмена',
      'donate_button': 'Пожертвовать',
      'required_fields_err_value': 'Пожалуйста, заполните все обязательные поля.',
      'add_card_button': 'Добавить Карту',
      'no_payment_method_title_value': 'Нет Способов Оплаты',
      'no_payment_method_description_value': 'У вас нет сохранённых способов оплаты. Пожалуйста, добавьте карту для продолжения пожертвования.',
      'goal_achieved_expired_carousel_value': '🎉 Цель Достигнута!',
      'inactive_expired_carousel_value': 'Неактивно',
      'amount_not_raised_expired_carousel_value': 'Сумма Не Собрана',
      'timer_days_value': 'дней',
    },
    // Chinese (zh)
    'zh': {
      'leaderboard_value': '排行榜',
      'donate_now_value': '立即捐款',
      'make_a_donation_value': '捐款',
      'custom_amount_hint_value': '输入自定义金额',
      'donation_category_hint_value': '捐款类别',
      'description_hint_value': '描述（可选）',
      'payment_method_hint_value': '付款方式',
      'cancel_button': '取消',
      'donate_button': '捐款',
      'required_fields_err_value': '请填写所有必填项。',
      'add_card_button': '添加银行卡',
      'no_payment_method_title_value': '无支付方式',
      'no_payment_method_description_value': '您没有保存的支付方式。请添加一张银行卡以继续捐款。',
      'goal_achieved_expired_carousel_value': '🎉 达成目标！',
      'inactive_expired_carousel_value': '未激活',
      'amount_not_raised_expired_carousel_value': '未筹到金额',
      'timer_days_value': '天',
    },
    // Japanese (ja)
    'ja': {
      'leaderboard_value': 'リーダーボード',
      'donate_now_value': '今すぐ寄付',
      'make_a_donation_value': '寄付する',
      'custom_amount_hint_value': 'カスタム金額を入力',
      'donation_category_hint_value': '寄付カテゴリー',
      'description_hint_value': '説明（任意）',
      'payment_method_hint_value': '支払い方法',
      'cancel_button': 'キャンセル',
      'donate_button': '寄付',
      'required_fields_err_value': '必須項目をすべて入力してください。',
      'add_card_button': 'カードを追加',
      'no_payment_method_title_value': '支払い方法がありません',
      'no_payment_method_description_value': '保存された支払い方法がありません。寄付を続けるにはカードを追加してください。',
      'goal_achieved_expired_carousel_value': '🎉 目標達成！',
      'inactive_expired_carousel_value': '非アクティブ',
      'amount_not_raised_expired_carousel_value': '目標金額未達',
      'timer_days_value': '日',
    },
    // Korean (ko)
    'ko': {
      'leaderboard_value': '리더보드',
      'donate_now_value': '지금 기부하기',
      'make_a_donation_value': '기부하기',
      'custom_amount_hint_value': '사용자 지정 금액 입력',
      'donation_category_hint_value': '기부 카테고리',
      'description_hint_value': '설명 (선택 사항)',
      'payment_method_hint_value': '결제 수단',
      'cancel_button': '취소',
      'donate_button': '기부하기',
      'required_fields_err_value': '모든 필수 항목을 입력해 주세요.',
      'add_card_button': '카드 추가',
      'no_payment_method_title_value': '결제 수단이 없습니다',
      'no_payment_method_description_value': '저장된 결제 수단이 없습니다. 기부를 진행하려면 카드를 추가해 주세요.',
      'goal_achieved_expired_carousel_value': '🎉 목표 달성!',
      'inactive_expired_carousel_value': '비활성',
      'amount_not_raised_expired_carousel_value': '모금액 미달',
      'timer_days_value': '일',
    },
    // Arabic (ar)
    'ar': {
      'leaderboard_value': 'لوحة المتصدرين',
      'donate_now_value': 'تبرع الآن',
      'make_a_donation_value': 'قم بالتبرع',
      'custom_amount_hint_value': 'أدخل مبلغًا مخصصًا',
      'donation_category_hint_value': 'فئة التبرع',
      'description_hint_value': 'الوصف (اختياري)',
      'payment_method_hint_value': 'طريقة الدفع',
      'cancel_button': 'إلغاء',
      'donate_button': 'تبرع',
      'required_fields_err_value': 'يرجى ملء جميع الحقول المطلوبة.',
      'add_card_button': 'أضف بطاقة',
      'no_payment_method_title_value': 'لا توجد طرق دفع',
      'no_payment_method_description_value': 'ليس لديك طرق دفع محفوظة. يرجى إضافة بطاقة للمتابعة في التبرع.',
      'goal_achieved_expired_carousel_value': '🎉 تم تحقيق الهدف!',
      'inactive_expired_carousel_value': 'غير نشط',
      'amount_not_raised_expired_carousel_value': 'المبلغ لم يُجمع',
      'timer_days_value': 'أيام',
    },
    // Hindi (hi)
    'hi': {
      'leaderboard_value': 'लीडरबोर्ड',
      'donate_now_value': 'अब दान करें',
      'make_a_donation_value': 'दान करें',
      'custom_amount_hint_value': 'कस्टम राशि दर्ज करें',
      'donation_category_hint_value': 'दान श्रेणी',
      'description_hint_value': 'विवरण (वैकल्पिक)',
      'payment_method_hint_value': 'भुगतान विधि',
      'cancel_button': 'रद्द करें',
      'donate_button': 'दान करें',
      'required_fields_err_value': 'कृपया सभी अनिवार्य फ़ील्ड भरें।',
      'add_card_button': 'कार्ड जोड़ें',
      'no_payment_method_title_value': 'कोई भुगतान विधि नहीं',
      'no_payment_method_description_value': 'आपके पास कोई भुगतान विधि सहेजी नहीं गई है। कृपया दान जारी रखने के लिए कार्ड जोड़ें।',
      'goal_achieved_expired_carousel_value': '🎉 लक्ष्य पूरा हुआ!',
      'inactive_expired_carousel_value': 'निष्क्रिय',
      'amount_not_raised_expired_carousel_value': 'राशि नहीं जुटी',
      'timer_days_value': 'दिन',
    },
    // Turkish (tr)
    'tr': {
      'leaderboard_value': 'Liderlik Tablosu',
      'donate_now_value': 'Şimdi Bağış Yap',
      'make_a_donation_value': 'Bağış Yap',
      'custom_amount_hint_value': 'Özel Tutar Girin',
      'donation_category_hint_value': 'Bağış Kategorisi',
      'description_hint_value': 'Açıklama (İsteğe Bağlı)',
      'payment_method_hint_value': 'Ödeme Yöntemi',
      'cancel_button': 'İptal',
      'donate_button': 'Bağış Yap',
      'required_fields_err_value': 'Lütfen tüm gerekli alanları doldurun.',
      'add_card_button': 'Kart Ekle',
      'no_payment_method_title_value': 'Ödeme Yöntemi Yok',
      'no_payment_method_description_value': 'Kaydedilmiş ödeme yöntemi yok. Lütfen bağışa devam etmek için bir kart ekleyin.',
      'goal_achieved_expired_carousel_value': '🎉 Hedef Gerçekleşti!',
      'inactive_expired_carousel_value': 'Pasif',
      'amount_not_raised_expired_carousel_value': 'Toplanamadı',
      'timer_days_value': 'gün',
    },
    // Thai (th)
    'th': {
      'leaderboard_value': 'อันดับผู้นำ',
      'donate_now_value': 'บริจาคตอนนี้',
      'make_a_donation_value': 'ทำการบริจาค',
      'custom_amount_hint_value': 'กรอกจำนวนเงินที่กำหนดเอง',
      'donation_category_hint_value': 'ประเภทการบริจาค',
      'description_hint_value': 'คำอธิบาย (ไม่จำเป็น)',
      'payment_method_hint_value': 'วิธีการชำระเงิน',
      'cancel_button': 'ยกเลิก',
      'donate_button': 'บริจาค',
      'required_fields_err_value': 'กรุณากรอกข้อมูลในช่องที่จำเป็นทั้งหมด',
      'add_card_button': 'เพิ่มบัตร',
      'no_payment_method_title_value': 'ไม่มีวิธีการชำระเงิน',
      'no_payment_method_description_value': 'คุณยังไม่มีวิธีการชำระเงินที่บันทึกไว้ กรุณาเพิ่มบัตรเพื่อดำเนินการบริจาค',
      'goal_achieved_expired_carousel_value': '🎉 บรรลุเป้าหมาย!',
      'inactive_expired_carousel_value': 'ไม่ใช้งาน',
      'amount_not_raised_expired_carousel_value': 'ยอดเงินไม่ถึงเป้า',
      'timer_days_value': 'วัน',
    },
    // Swedish (sv)
    'sv': {
      'leaderboard_value': 'Topplista',
      'donate_now_value': 'Donera Nu',
      'make_a_donation_value': 'Gör en Donation',
      'custom_amount_hint_value': 'Ange Anpassat Belopp',
      'donation_category_hint_value': 'Donationskategori',
      'description_hint_value': 'Beskrivning (Valfritt)',
      'payment_method_hint_value': 'Betalningsmetod',
      'cancel_button': 'Avbryt',
      'donate_button': 'Donera',
      'required_fields_err_value': 'Var vänlig fyll i alla obligatoriska fält.',
      'add_card_button': 'Lägg till Kort',
      'no_payment_method_title_value': 'Inga Betalningsmetoder',
      'no_payment_method_description_value': 'Du har inga sparade betalningsmetoder. Vänligen lägg till ett kort för att fortsätta med en donation.',
      'goal_achieved_expired_carousel_value': '🎉 Mål Uppnått!',
      'inactive_expired_carousel_value': 'Inaktiv',
      'amount_not_raised_expired_carousel_value': 'Belopp Ej Uppnått',
      'timer_days_value': 'dagar',
    },
    // Greek (el)
    'el': {
      'leaderboard_value': 'Πίνακας Αριστείας',
      'donate_now_value': 'Δωρίστε Τώρα',
      'make_a_donation_value': 'Κάντε Δωρεά',
      'custom_amount_hint_value': 'Εισάγετε Προσαρμοσμένο Ποσό',
      'donation_category_hint_value': 'Κατηγορία Δωρεάς',
      'description_hint_value': 'Περιγραφή (Προαιρετικά)',
      'payment_method_hint_value': 'Τρόπος Πληρωμής',
      'cancel_button': 'Ακύρωση',
      'donate_button': 'Δωρεά',
      'required_fields_err_value': 'Παρακαλώ συμπληρώστε όλα τα υποχρεωτικά πεδία.',
      'add_card_button': 'Προσθέστε Κάρτα',
      'no_payment_method_title_value': 'Δεν υπάρχουν Μέθοδοι Πληρωμής',
      'no_payment_method_description_value': 'Δεν έχετε αποθηκευμένες μεθόδους πληρωμής. Παρακαλώ προσθέστε μια κάρτα για να συνεχίσετε με τη δωρεά.',
      'goal_achieved_expired_carousel_value': '🎉 Στόχος Επιτεύχθηκε!',
      'inactive_expired_carousel_value': 'Ανενεργό',
      'amount_not_raised_expired_carousel_value': 'Το Ποσό Δεν Συγκεντρώθηκε',
      'timer_days_value': 'ημέρες',
    },
    // Polish (pl)
    'pl': {
      'leaderboard_value': 'Ranking',
      'donate_now_value': 'Przekaż Darowiznę Teraz',
      'make_a_donation_value': 'Zrób Darowiznę',
      'custom_amount_hint_value': 'Wpisz Niestandardową Kwotę',
      'donation_category_hint_value': 'Kategoria Darowizny',
      'description_hint_value': 'Opis (Opcjonalnie)',
      'payment_method_hint_value': 'Metoda Płatności',
      'cancel_button': 'Anuluj',
      'donate_button': 'Przekaż Darowiznę',
      'required_fields_err_value': 'Proszę wypełnić wszystkie wymagane pola.',
      'add_card_button': 'Dodaj Kartę',
      'no_payment_method_title_value': 'Brak Metod Płatności',
      'no_payment_method_description_value': 'Nie masz zapisanych metod płatności. Proszę dodaj kartę, aby kontynuować darowiznę.',
      'goal_achieved_expired_carousel_value': '🎉 Cel Osiągnięty!',
      'inactive_expired_carousel_value': 'Nieaktywny',
      'amount_not_raised_expired_carousel_value': 'Kwota Nie Zebrana',
      'timer_days_value': 'dni',
    },
    // Vietnamese (vi)
    'vi': {
      'leaderboard_value': 'Bảng Xếp Hạng',
      'donate_now_value': 'Quyên Góp Ngay',
      'make_a_donation_value': 'Thực Hiện Quyên Góp',
      'custom_amount_hint_value': 'Nhập Số Tiền Tùy Chỉnh',
      'donation_category_hint_value': 'Danh Mục Quyên Góp',
      'description_hint_value': 'Mô Tả (Tùy Chọn)',
      'payment_method_hint_value': 'Phương Thức Thanh Toán',
      'cancel_button': 'Hủy',
      'donate_button': 'Quyên Góp',
      'required_fields_err_value': 'Vui lòng điền đầy đủ các trường bắt buộc.',
      'add_card_button': 'Thêm Thẻ',
      'no_payment_method_title_value': 'Không Có Phương Thức Thanh Toán',
      'no_payment_method_description_value': 'Bạn chưa lưu phương thức thanh toán nào. Vui lòng thêm thẻ để tiến hành quyên góp.',
      'goal_achieved_expired_carousel_value': '🎉 Mục Tiêu Đã Đạt!',
      'inactive_expired_carousel_value': 'Không Hoạt Động',
      'amount_not_raised_expired_carousel_value': 'Số Tiền Chưa Được Gây Quỹ',
      'timer_days_value': 'ngày',
    },
  };

  static String getLabel(String langCode, String key) {
    return labels[langCode]?[key] ?? key;
  }
}
