class ProfileLabels{
  static Map<String,dynamic> Profilelabels = {
    'en': {
      "top_donors_title_value": "Top Donor",
      "total_donations_value": "Total Donations: ",
      "donation_history_title_value": "Donation History",
      "no_description_value": "No description",
      "no_category_value": "No category",
      "no_donations_value": "No Donations",
      "Save": "Save",
      "Cancel": "Cancel",
      "Balance": "Balance",
      "Card Number": "Card Number",
      "Card Type": "Card Type",
      "Add New Card": "Add New Card",
      "Remove": "Remove",
      "Edit": "Edit",
      "Your Wallet": "Your Wallet",
      "Add Card": "Add Card",
      "No cards available": "No cards available"
    },
    'es': {
      "top_donors_title_value": "Mejor Donante",
      "total_donations_value": "Total de Donaciones: ",
      "donation_history_title_value": "Historial de Donaciones",
      "no_description_value": "Sin descripción",
      "no_category_value": "Sin categoría",
      "no_donations_value": "Sin Donaciones",
      "Save": "Guardar",
      "Cancel": "Cancelar",
      "Balance": "Saldo",
      "Card Number": "Número de Tarjeta",
      "Card Type": "Tipo de Tarjeta",
      "Add New Card": "Añadir Nueva Tarjeta",
      "Remove": "Eliminar",
      "Edit": "Editar",
      "Your Wallet": "Tu Billetera",
      "Add Card": "Añadir Tarjeta",
      "No cards available": "No hay tarjetas disponibles"
    },
    'fr': {
      "top_donors_title_value": "Meilleur Donateur",
      "total_donations_value": "Total des Dons: ",
      "donation_history_title_value": "Historique des Dons",
      "no_description_value": "Pas de description",
      "no_category_value": "Pas de catégorie",
      "no_donations_value": "Pas de Dons",
      "Save": "Sauvegarder",
      "Cancel": "Annuler",
      "Balance": "Solde",
      "Card Number": "Numéro de Carte",
      "Card Type": "Type de Carte",
      "Add New Card": "Ajouter une Nouvelle Carte",
      "Remove": "Supprimer",
      "Edit": "Modifier",
      "Your Wallet": "Votre Portefeuille",
      "Add Card": "Ajouter une Carte",
      "No cards available": "Aucune carte disponible"
    },
    'de': {
      "top_donors_title_value": "Top Spender",
      "total_donations_value": "Gesamtspenden: ",
      "donation_history_title_value": "Spendenverlauf",
      "no_description_value": "Keine Beschreibung",
      "no_category_value": "Keine Kategorie",
      "no_donations_value": "Keine Spenden",
      "Save": "Speichern",
      "Cancel": "Abbrechen",
      "Balance": "Kontostand",
      "Card Number": "Kartennummer",
      "Card Type": "Kartentyp",
      "Add New Card": "Neue Karte Hinzufügen",
      "Remove": "Entfernen",
      "Edit": "Bearbeiten",
      "Your Wallet": "Ihr Wallet",
      "Add Card": "Karte Hinzufügen",
      "No cards available": "Keine Karten verfügbar"
    },
    'it': {
      "top_donors_title_value": "Miglior Donatore",
      "total_donations_value": "Donazioni Totali: ",
      "donation_history_title_value": "Storico delle Donazioni",
      "no_description_value": "Nessuna descrizione",
      "no_category_value": "Nessuna categoria",
      "no_donations_value": "Nessuna Donazione",
      "Save": "Salva",
      "Cancel": "Annulla",
      "Balance": "Saldo",
      "Card Number": "Numero della Carta",
      "Card Type": "Tipo di Carta",
      "Add New Card": "Aggiungi Nuova Carta",
      "Remove": "Rimuovi",
      "Edit": "Modifica",
      "Your Wallet": "Il Tuo Portafoglio",
      "Add Card": "Aggiungi Carta",
      "No cards available": "Nessuna carta disponibile"
    },
    'pt': {
      "top_donors_title_value": "Melhor Dono",
      "total_donations_value": "Total de Doações: ",
      "donation_history_title_value": "Histórico de Doações",
      "no_description_value": "Sem descrição",
      "no_category_value": "Sem categoria",
      "no_donations_value": "Sem Doações",
      "Save": "Salvar",
      "Cancel": "Cancelar",
      "Balance": "Saldo",
      "Card Number": "Número do Cartão",
      "Card Type": "Tipo de Cartão",
      "Add New Card": "Adicionar Novo Cartão",
      "Remove": "Remover",
      "Edit": "Editar",
      "Your Wallet": "Sua Carteira",
      "Add Card": "Adicionar Cartão",
      "No cards available": "Nenhum cartão disponível"
    },
    'nl': {
      "top_donors_title_value": "Top Donateur",
      "total_donations_value": "Totaal Donaties: ",
      "donation_history_title_value": "Donatiegeschiedenis",
      "no_description_value": "Geen beschrijving",
      "no_category_value": "Geen categorie",
      "no_donations_value": "Geen Donaties",
      "Save": "Opslaan",
      "Cancel": "Annuleren",
      "Balance": "Saldo",
      "Card Number": "Kaartnummer",
      "Card Type": "Kaarttype",
      "Add New Card": "Nieuwe Kaart Toevoegen",
      "Remove": "Verwijderen",
      "Edit": "Bewerken",
      "Your Wallet": "Je Portemonnee",
      "Add Card": "Kaart Toevoegen",
      "No cards available": "Geen kaarten beschikbaar"
    },
    'ru': {
      "top_donors_title_value": "Лучший Донор",
      "total_donations_value": "Общие Пожертвования: ",
      "donation_history_title_value": "История Пожертвований",
      "no_description_value": "Нет описания",
      "no_category_value": "Нет категории",
      "no_donations_value": "Нет Пожертвований",
      "Save": "Сохранить",
      "Cancel": "Отменить",
      "Balance": "Баланс",
      "Card Number": "Номер Карты",
      "Card Type": "Тип Карты",
      "Add New Card": "Добавить Новую Карту",
      "Remove": "Удалить",
      "Edit": "Редактировать",
      "Your Wallet": "Ваш Кошелек",
      "Add Card": "Добавить Карту",
      "No cards available": "Нет карт"
    },
    'zh': {
      "top_donors_title_value": "最佳捐赠者",
      "total_donations_value": "总捐赠: ",
      "donation_history_title_value": "捐赠历史",
      "no_description_value": "没有描述",
      "no_category_value": "没有类别",
      "no_donations_value": "没有捐赠",
      "Save": "保存",
      "Cancel": "取消",
      "Balance": "余额",
      "Card Number": "卡号",
      "Card Type": "卡类型",
      "Add New Card": "添加新卡",
      "Remove": "移除",
      "Edit": "编辑",
      "Your Wallet": "您的钱包",
      "Add Card": "添加卡片",
      "No cards available": "没有可用卡片"
    },
    'ja': {
      "top_donors_title_value": "トップ寄付者",
      "total_donations_value": "総寄付金: ",
      "donation_history_title_value": "寄付履歴",
      "no_description_value": "説明なし",
      "no_category_value": "カテゴリーなし",
      "no_donations_value": "寄付なし",
      "Save": "保存",
      "Cancel": "キャンセル",
      "Balance": "残高",
      "Card Number": "カード番号",
      "Card Type": "カードタイプ",
      "Add New Card": "新しいカードを追加",
      "Remove": "削除",
      "Edit": "編集",
      "Your Wallet": "あなたのウォレット",
      "Add Card": "カードを追加",
      "No cards available": "利用可能なカードはありません"
    },
    'ko': {
      "top_donors_title_value": "최고 기부자",
      "total_donations_value": "총 기부금: ",
      "donation_history_title_value": "기부 내역",
      "no_description_value": "설명 없음",
      "no_category_value": "카테고리 없음",
      "no_donations_value": "기부 없음",
      "Save": "저장",
      "Cancel": "취소",
      "Balance": "잔액",
      "Card Number": "카드 번호",
      "Card Type": "카드 유형",
      "Add New Card": "새 카드 추가",
      "Remove": "제거",
      "Edit": "편집",
      "Your Wallet": "당신의 지갑",
      "Add Card": "카드 추가",
      "No cards available": "사용 가능한 카드가 없습니다"
    },
    'ar': {
      "top_donors_title_value": "أفضل المتبرعين",
      "total_donations_value": "إجمالي التبرعات: ",
      "donation_history_title_value": "تاريخ التبرعات",
      "no_description_value": "لا يوجد وصف",
      "no_category_value": "لا فئة",
      "no_donations_value": "لا توجد تبرعات",
      "Save": "حفظ",
      "Cancel": "إلغاء",
      "Balance": "الرصيد",
      "Card Number": "رقم البطاقة",
      "Card Type": "نوع البطاقة",
      "Add New Card": "إضافة بطاقة جديدة",
      "Remove": "إزالة",
      "Edit": "تعديل",
      "Your Wallet": "محفظتك",
      "Add Card": "إضافة بطاقة",
      "No cards available": "لا توجد بطاقات متاحة"
    },
    'hi': {
      "top_donors_title_value": "सर्वश्रेष्ठ दाता",
      "total_donations_value": "कुल दान: ",
      "donation_history_title_value": "दान इतिहास",
      "no_description_value": "कोई विवरण नहीं",
      "no_category_value": "कोई श्रेणी नहीं",
      "no_donations_value": "कोई दान नहीं",
      "Save": "सहेजें",
      "Cancel": "रद्द करें",
      "Balance": "बैलेंस",
      "Card Number": "कार्ड नंबर",
      "Card Type": "कार्ड प्रकार",
      "Add New Card": "नई कार्ड जोड़ें",
      "Remove": "हटाएं",
      "Edit": "संपादित करें",
      "Your Wallet": "आपका वॉलेट",
      "Add Card": "कार्ड जोड़ें",
      "No cards available": "कोई कार्ड उपलब्ध नहीं"
    },
    'tr': {
      "top_donors_title_value": "En İyi Bağışçı",
      "total_donations_value": "Toplam Bağışlar: ",
      "donation_history_title_value": "Bağış Geçmişi",
      "no_description_value": "Açıklama Yok",
      "no_category_value": "Kategori Yok",
      "no_donations_value": "Bağış Yok",
      "Save": "Kaydet",
      "Cancel": "İptal",
      "Balance": "Bakiye",
      "Card Number": "Kart Numarası",
      "Card Type": "Kart Türü",
      "Add New Card": "Yeni Kart Ekle",
      "Remove": "Kaldır",
      "Edit": "Düzenle",
      "Your Wallet": "Cüzdanınız",
      "Add Card": "Kart Ekle",
      "No cards available": "Kullanılabilir kart yok"
    },
    'th': {
      "top_donors_title_value": "ผู้บริจาคยอดเยี่ยม",
      "total_donations_value": "ยอดบริจาคทั้งหมด: ",
      "donation_history_title_value": "ประวัติการบริจาค",
      "no_description_value": "ไม่มีคำอธิบาย",
      "no_category_value": "ไม่มีหมวดหมู่",
      "no_donations_value": "ไม่มีการบริจาค",
      "Save": "บันทึก",
      "Cancel": "ยกเลิก",
      "Balance": "ยอดคงเหลือ",
      "Card Number": "หมายเลขบัตร",
      "Card Type": "ประเภทบัตร",
      "Add New Card": "เพิ่มบัตรใหม่",
      "Remove": "ลบ",
      "Edit": "แก้ไข",
      "Your Wallet": "กระเป๋าเงินของคุณ",
      "Add Card": "เพิ่มบัตร",
      "No cards available": "ไม่มีบัตรที่พร้อมใช้งาน"
    },
    'sv': {
      "top_donors_title_value": "Top Donator",
      "total_donations_value": "Totala Donationer: ",
      "donation_history_title_value": "Donationshistorik",
      "no_description_value": "Ingen beskrivning",
      "no_category_value": "Ingen kategori",
      "no_donations_value": "Inga Donationer",
      "Save": "Spara",
      "Cancel": "Avbryt",
      "Balance": "Saldo",
      "Card Number": "Kortnummer",
      "Card Type": "Korttyp",
      "Add New Card": "Lägg Till Nytt Kort",
      "Remove": "Ta bort",
      "Edit": "Redigera",
      "Your Wallet": "Din Plånbok",
      "Add Card": "Lägg Till Kort",
      "No cards available": "Inga kort tillgängliga"
    },
    'el': {
      "top_donors_title_value": "Κορυφαίος Δωρητής",
      "total_donations_value": "Συνολικές Δωρεές: ",
      "donation_history_title_value": "Ιστορικό Δωρεών",
      "no_description_value": "Χωρίς περιγραφή",
      "no_category_value": "Χωρίς κατηγορία",
      "no_donations_value": "Χωρίς Δωρεές",
      "Save": "Αποθήκευση",
      "Cancel": "Ακύρωση",
      "Balance": "Υπόλοιπο",
      "Card Number": "Αριθμός Κάρτας",
      "Card Type": "Τύπος Κάρτας",
      "Add New Card": "Προσθήκη Νέας Κάρτας",
      "Remove": "Αφαίρεση",
      "Edit": "Επεξεργασία",
      "Your Wallet": "Το Πορτοφόλι σας",
      "Add Card": "Προσθήκη Κάρτας",
      "No cards available": "Δεν υπάρχουν κάρτες διαθέσιμες"
    },
    'pl': {
      "top_donors_title_value": "Najlepszy Donator",
      "total_donations_value": "Łączne Darowizny: ",
      "donation_history_title_value": "Historia Darowizn",
      "no_description_value": "Brak opisu",
      "no_category_value": "Brak kategorii",
      "no_donations_value": "Brak Darowizn",
      "Save": "Zapisz",
      "Cancel": "Anuluj",
      "Balance": "Saldo",
      "Card Number": "Numer Karty",
      "Card Type": "Typ Karty",
      "Add New Card": "Dodaj Nową Kartę",
      "Remove": "Usuń",
      "Edit": "Edytuj",
      "Your Wallet": "Twoje Portfel",
      "Add Card": "Dodaj Kartę",
      "No cards available": "Brak dostępnych kart"
    },
    'vi': {
      "top_donors_title_value": "Nhà Tài Trợ Hàng Đầu",
      "total_donations_value": "Tổng Số Quyên Góp: ",
      "donation_history_title_value": "Lịch Sử Quyên Góp",
      "no_description_value": "Không có mô tả",
      "no_category_value": "Không có danh mục",
      "no_donations_value": "Không có quyên góp",
      "Save": "Lưu",
      "Cancel": "Hủy",
      "Balance": "Số dư",
      "Card Number": "Số thẻ",
      "Card Type": "Loại thẻ",
      "Add New Card": "Thêm thẻ mới",
      "Remove": "Xóa",
      "Edit": "Chỉnh sửa",
      "Your Wallet": "Ví của bạn",
      "Add Card": "Thêm thẻ",
      "No cards available": "Không có thẻ nào"
    }
  }
  ;

  static String getLabel(String langCode, String key) {
    return Profilelabels[langCode]?[key] ?? key;
  }
}