class SettingsLabels {
  static Map<String, Map<String, String>> localizedValues = {
    'en': {
      'enable_notifications': "Enable Notifications",
      'dark_mode': "Dark Mode",
      'light_mode': "Light Mode",
      'select_language_hint': "Select Language",
      'select_currency_hint': "Select Currency",
      'font_size': "Font Size",
      'privacy_mode': "Privacy Mode",
      'accent_color_hint': "Accent Color",
      'notification_sound_hint': "Notification Sound",
      'layout_mode_hint': "Layout Mode",
      'privacy_policy_button': "Privacy & Policy",
      'terms_conditions_button': "Terms & Conditions",
      'about_button': "About",
      'logout_button': "Logout",
      'username_button': "Username",
      'email_button': "Email",
      'profile_settings_section': "Profile Settings",
      'app_settings_section': "App Settings",
      'notifications_section': "Notifications",
      'privacy_security_section': "Privacy & Security",
      'account_section': "Account",
      '6-Digit Code': "6-Digit Code",
    },
    'es': {
      'enable_notifications': "Habilitar notificaciones",
      'dark_mode': "Modo oscuro",
      'light_mode': "Modo claro",
      'select_language_hint': "Seleccionar idioma",
      'select_currency_hint': "Seleccionar moneda",
      'font_size': "Tamaño de fuente",
      'privacy_mode': "Modo privacidad",
      'accent_color_hint': "Color de acento",
      'notification_sound_hint': "Sonido de notificación",
      'layout_mode_hint': "Modo de diseño",
      'privacy_policy_button': "Política de privacidad",
      'terms_conditions_button': "Términos y condiciones",
      'about_button': "Acerca de",
      'logout_button': "Cerrar sesión",
      'username_button': "Nombre de usuario",
      'email_button': "Correo electrónico",
      'profile_settings_section': "Configuración de perfil",
      'app_settings_section': "Configuración de la aplicación",
      'notifications_section': "Notificaciones",
      'privacy_security_section': "Privacidad y seguridad",
      'account_section': "Cuenta",
      '6-Digit Code': "Código de 6 dígitos",
    },
    'fr': {
      'enable_notifications': "Activer les notifications",
      'dark_mode': "Mode sombre",
      'light_mode': "Mode clair",
      'select_language_hint': "Sélectionner la langue",
      'select_currency_hint': "Sélectionner la devise",
      'font_size': "Taille de la police",
      'privacy_mode': "Mode de confidentialité",
      'accent_color_hint': "Couleur d'accent",
      'notification_sound_hint': "Son de notification",
      'layout_mode_hint': "Mode de mise en page",
      'privacy_policy_button': "Politique de confidentialité",
      'terms_conditions_button': "Conditions générales",
      'about_button': "À propos",
      'logout_button': "Se déconnecter",
      'username_button': "Nom d'utilisateur",
      'email_button': "E-mail",
      'profile_settings_section': "Paramètres du profil",
      'app_settings_section': "Paramètres de l'application",
      'notifications_section': "Notifications",
      'privacy_security_section': "Confidentialité et sécurité",
      'account_section': "Compte",
      '6-Digit Code': "Code à 6 chiffres",
    },
    'de': {
      'enable_notifications': "Benachrichtigungen aktivieren",
      'dark_mode': "Dunkler Modus",
      'light_mode': "Heller Modus",
      'select_language_hint': "Sprache auswählen",
      'select_currency_hint': "Währung auswählen",
      'font_size': "Schriftgröße",
      'privacy_mode': "Privatsphärenmodus",
      'accent_color_hint': "Akzentfarbe",
      'notification_sound_hint': "Benachrichtigungston",
      'layout_mode_hint': "Layout-Modus",
      'privacy_policy_button': "Datenschutzrichtlinie",
      'terms_conditions_button': "Allgemeine Geschäftsbedingungen",
      'about_button': "Über",
      'logout_button': "Abmelden",
      'username_button': "Benutzername",
      'email_button': "E-Mail",
      'profile_settings_section': "Profileinstellungen",
      'app_settings_section': "App-Einstellungen",
      'notifications_section': "Benachrichtigungen",
      'privacy_security_section': "Datenschutz & Sicherheit",
      'account_section': "Konto",
      '6-Digit Code': "6-stelliger Code",
    },
    'it': {
      'enable_notifications': "Abilita notifiche",
      'dark_mode': "Modalità scura",
      'light_mode': "Modalità chiara",
      'select_language_hint': "Seleziona lingua",
      'select_currency_hint': "Seleziona valuta",
      'font_size': "Dimensione carattere",
      'privacy_mode': "Modalità privacy",
      'accent_color_hint': "Colore accento",
      'notification_sound_hint': "Suono notifiche",
      'layout_mode_hint': "Modalità layout",
      'privacy_policy_button': "Informativa sulla privacy",
      'terms_conditions_button': "Termini e condizioni",
      'about_button': "Informazioni",
      'logout_button': "Disconnetti",
      'username_button': "Nome utente",
      'email_button': "Email",
      'profile_settings_section': "Impostazioni profilo",
      'app_settings_section': "Impostazioni app",
      'notifications_section': "Notifiche",
      'privacy_security_section': "Privacy e sicurezza",
      'account_section': "Account",
      '6-Digit Code': "Codice a 6 cifre",
    },
    'pt': {
      'enable_notifications': "Ativar notificações",
      'dark_mode': "Modo escuro",
      'light_mode': "Modo claro",
      'select_language_hint': "Selecionar idioma",
      'select_currency_hint': "Selecionar moeda",
      'font_size': "Tamanho da fonte",
      'privacy_mode': "Modo de privacidade",
      'accent_color_hint': "Cor de destaque",
      'notification_sound_hint': "Som de notificação",
      'layout_mode_hint': "Modo de layout",
      'privacy_policy_button': "Política de privacidade",
      'terms_conditions_button': "Termos e condições",
      'about_button': "Sobre",
      'logout_button': "Sair",
      'username_button': "Nome de usuário",
      'email_button': "E-mail",
      'profile_settings_section': "Configurações de perfil",
      'app_settings_section': "Configurações do aplicativo",
      'notifications_section': "Notificações",
      'privacy_security_section': "Privacidade e segurança",
      'account_section': "Conta",
      '6-Digit Code': "Código de 6 dígitos",
    },
    'nl': {
      'enable_notifications': "Meldingen inschakelen",
      'dark_mode': "Donkere modus",
      'light_mode': "Lichte modus",
      'select_language_hint': "Selecteer taal",
      'select_currency_hint': "Selecteer valuta",
      'font_size': "Lettergrootte",
      'privacy_mode': "Privacy-modus",
      'accent_color_hint': "Accentkleur",
      'notification_sound_hint': "Melding geluid",
      'layout_mode_hint': "Lay-out modus",
      'privacy_policy_button': "Privacybeleid",
      'terms_conditions_button': "Algemene voorwaarden",
      'about_button': "Over",
      'logout_button': "Uitloggen",
      'username_button': "Gebruikersnaam",
      'email_button': "E-mail",
      'profile_settings_section': "Profielinstellingen",
      'app_settings_section': "App-instellingen",
      'notifications_section': "Meldingen",
      'privacy_security_section': "Privacy en beveiliging",
      'account_section': "Account",
      '6-Digit Code': "6-cijferige code",
    },
    'ru': {
      'enable_notifications': "Включить уведомления",
      'dark_mode': "Темный режим",
      'light_mode': "Светлый режим",
      'select_language_hint': "Выбрать язык",
      'select_currency_hint': "Выбрать валюту",
      'font_size': "Размер шрифта",
      'privacy_mode': "Режим конфиденциальности",
      'accent_color_hint': "Цвет акцента",
      'notification_sound_hint': "Звук уведомления",
      'layout_mode_hint': "Режим компоновки",
      'privacy_policy_button': "Политика конфиденциальности",
      'terms_conditions_button': "Условия и положения",
      'about_button': "О нас",
      'logout_button': "Выйти",
      'username_button': "Имя пользователя",
      'email_button': "Электронная почта",
      'profile_settings_section': "Настройки профиля",
      'app_settings_section': "Настройки приложения",
      'notifications_section': "Уведомления",
      'privacy_security_section': "Конфиденциальность и безопасность",
      'account_section': "Аккаунт",
      '6-Digit Code': "6-значный код",
    },
    'zh': {
      'enable_notifications': "启用通知",
      'dark_mode': "深色模式",
      'light_mode': "浅色模式",
      'select_language_hint': "选择语言",
      'select_currency_hint': "选择货币",
      'font_size': "字体大小",
      'privacy_mode': "隐私模式",
      'accent_color_hint': "强调色",
      'notification_sound_hint': "通知声音",
      'layout_mode_hint': "布局模式",
      'privacy_policy_button': "隐私政策",
      'terms_conditions_button': "条款和条件",
      'about_button': "关于",
      'logout_button': "登出",
      'username_button': "用户名",
      'email_button': "电子邮件",
      'profile_settings_section': "个人资料设置",
      'app_settings_section': "应用程序设置",
      'notifications_section': "通知",
      'privacy_security_section': "隐私与安全",
      'account_section': "账户",
      '6-Digit Code': "6位数字代码",
    },
    'ja': {
      'enable_notifications': "通知を有効にする",
      'dark_mode': "ダークモード",
      'light_mode': "ライトモード",
      'select_language_hint': "言語を選択",
      'select_currency_hint': "通貨を選択",
      'font_size': "フォントサイズ",
      'privacy_mode': "プライバシーモード",
      'accent_color_hint': "アクセントカラー",
      'notification_sound_hint': "通知音",
      'layout_mode_hint': "レイアウトモード",
      'privacy_policy_button': "プライバシーポリシー",
      'terms_conditions_button': "利用規約",
      'about_button': "約",
      'logout_button': "ログアウト",
      'username_button': "ユーザー名",
      'email_button': "メール",
      'profile_settings_section': "プロフィール設定",
      'app_settings_section': "アプリ設定",
      'notifications_section': "通知",
      'privacy_security_section': "プライバシーとセキュリティ",
      'account_section': "アカウント",
      '6-Digit Code': "6桁のコード",
    },
    'ko': {
      'enable_notifications': "알림 활성화",
      'dark_mode': "다크 모드",
      'light_mode': "라이트 모드",
      'select_language_hint': "언어 선택",
      'select_currency_hint': "통화 선택",
      'font_size': "글꼴 크기",
      'privacy_mode': "프라이버시 모드",
      'accent_color_hint': "포인트 색상",
      'notification_sound_hint': "알림음",
      'layout_mode_hint': "레이아웃 모드",
      'privacy_policy_button': "개인정보처리방침",
      'terms_conditions_button': "이용 약관",
      'about_button': "정보",
      'logout_button': "로그아웃",
      'username_button': "사용자 이름",
      'email_button': "이메일",
      'profile_settings_section': "프로필 설정",
      'app_settings_section': "앱 설정",
      'notifications_section': "알림",
      'privacy_security_section': "개인 정보 보호 및 보안",
      'account_section': "계정",
      '6-Digit Code': "6자리 코드",
    },
    'ar': {
      'enable_notifications': "تفعيل الإشعارات",
      'dark_mode': "الوضع الداكن",
      'light_mode': "الوضع الفاتح",
      'select_language_hint': "اختر اللغة",
      'select_currency_hint': "اختر العملة",
      'font_size': "حجم الخط",
      'privacy_mode': "وضع الخصوصية",
      'accent_color_hint': "لون التمييز",
      'notification_sound_hint': "صوت الإشعار",
      'layout_mode_hint': "وضع التنسيق",
      'privacy_policy_button': "سياسة الخصوصية",
      'terms_conditions_button': "الشروط والأحكام",
      'about_button': "حول",
      'logout_button': "تسجيل الخروج",
      'username_button': "اسم المستخدم",
      'email_button': "البريد الإلكتروني",
      'profile_settings_section': "إعدادات الملف الشخصي",
      'app_settings_section': "إعدادات التطبيق",
      'notifications_section': "الإشعارات",
      'privacy_security_section': "الخصوصية والأمان",
      'account_section': "الحساب",
      '6-Digit Code': "رمز مكون من 6 أرقام",
    },
    'hi': {
      'enable_notifications': "सूचनाएं सक्षम करें",
      'dark_mode': "डार्क मोड",
      'light_mode': "लाइट मोड",
      'select_language_hint': "भाषा चुनें",
      'select_currency_hint': "मुद्रा चुनें",
      'font_size': "फॉन्ट का आकार",
      'privacy_mode': "गोपनीयता मोड",
      'accent_color_hint': "हाइलाइट रंग",
      'notification_sound_hint': "सूचना ध्वनि",
      'layout_mode_hint': "लेआउट मोड",
      'privacy_policy_button': "गोपनीयता नीति",
      'terms_conditions_button': "नियम और शर्तें",
      'about_button': "के बारे में",
      'logout_button': "लॉगआउट करें",
      'username_button': "यूज़रनेम",
      'email_button': "ईमेल",
      'profile_settings_section': "प्रोफ़ाइल सेटिंग्स",
      'app_settings_section': "ऐप सेटिंग्स",
      'notifications_section': "सूचनाएं",
      'privacy_security_section': "गोपनीयता और सुरक्षा",
      'account_section': "खाता",
      '6-Digit Code': "6-अंकों का कोड",
    },
    'tr': {
      'enable_notifications': "Bildirimleri Etkinleştir",
      'dark_mode': "Karanlık Mod",
      'light_mode': "Aydınlık Mod",
      'select_language_hint': "Dil Seç",
      'select_currency_hint': "Para Birimi Seç",
      'font_size': "Yazı Boyutu",
      'privacy_mode': "Gizlilik Modu",
      'accent_color_hint': "Vurgu Rengi",
      'notification_sound_hint': "Bildirim Sesi",
      'layout_mode_hint': "Düzen Modu",
      'privacy_policy_button': "Gizlilik Politikası",
      'terms_conditions_button': "Şartlar ve Koşullar",
      'about_button': "Hakkında",
      'logout_button': "Çıkış Yap",
      'username_button': "Kullanıcı Adı",
      'email_button': "E-posta",
      'profile_settings_section': "Profil Ayarları",
      'app_settings_section': "Uygulama Ayarları",
      'notifications_section': "Bildirimler",
      'privacy_security_section': "Gizlilik ve Güvenlik",
      'account_section': "Hesap",
      '6-Digit Code': "6 Haneli Kod",
    },
    'th': {
      'enable_notifications': "เปิดการแจ้งเตือน",
      'dark_mode': "โหมดมืด",
      'light_mode': "โหมดสว่าง",
      'select_language_hint': "เลือกภาษา",
      'select_currency_hint': "เลือกสกุลเงิน",
      'font_size': "ขนาดตัวอักษร",
      'privacy_mode': "โหมดความเป็นส่วนตัว",
      'accent_color_hint': "สีเน้น",
      'notification_sound_hint': "เสียงแจ้งเตือน",
      'layout_mode_hint': "โหมดเลย์เอาต์",
      'privacy_policy_button': "นโยบายความเป็นส่วนตัว",
      'terms_conditions_button': "ข้อกำหนดและเงื่อนไข",
      'about_button': "เกี่ยวกับ",
      'logout_button': "ออกจากระบบ",
      'username_button': "ชื่อผู้ใช้",
      'email_button': "อีเมล",
      'profile_settings_section': "การตั้งค่าโปรไฟล์",
      'app_settings_section': "การตั้งค่าแอป",
      'notifications_section': "การแจ้งเตือน",
      'privacy_security_section': "ความเป็นส่วนตัวและความปลอดภัย",
      'account_section': "บัญชี",
      '6-Digit Code': "รหัส 6 หลัก",
    },
    'sv': {
      'enable_notifications': "Aktivera aviseringar",
      'dark_mode': "Mörkt läge",
      'light_mode': "Ljust läge",
      'select_language_hint': "Välj språk",
      'select_currency_hint': "Välj valuta",
      'font_size': "Teckenstorlek",
      'privacy_mode': "Integritetsläge",
      'accent_color_hint': "Accentfärg",
      'notification_sound_hint': "Aviseringsljud",
      'layout_mode_hint': "Layoutläge",
      'privacy_policy_button': "Integritetspolicy",
      'terms_conditions_button': "Villkor",
      'about_button': "Om",
      'logout_button': "Logga ut",
      'username_button': "Användarnamn",
      'email_button': "E-post",
      'profile_settings_section': "Profilinställningar",
      'app_settings_section': "Appinställningar",
      'notifications_section': "Aviseringar",
      'privacy_security_section': "Integritet och säkerhet",
      'account_section': "Konto",
      '6-Digit Code': "6-siffrig kod",
    },
    'el': {
      'enable_notifications': "Ενεργοποίηση ειδοποιήσεων",
      'dark_mode': "Σκούρο θέμα",
      'light_mode': "Φωτεινό θέμα",
      'select_language_hint': "Επιλογή γλώσσας",
      'select_currency_hint': "Επιλογή νομίσματος",
      'font_size': "Μέγεθος γραμματοσειράς",
      'privacy_mode': "Λειτουργία απορρήτου",
      'accent_color_hint': "Χρώμα προφοράς",
      'notification_sound_hint': "Ήχος ειδοποίησης",
      'layout_mode_hint': "Διάταξη λειτουργίας",
      'privacy_policy_button': "Πολιτική Απορρήτου",
      'terms_conditions_button': "Όροι και Προϋποθέσεις",
      'about_button': "Σχετικά",
      'logout_button': "Αποσύνδεση",
      'username_button': "Όνομα χρήστη",
      'email_button': "Ηλεκτρονικό ταχυδρομείο",
      'profile_settings_section': "Ρυθμίσεις προφίλ",
      'app_settings_section': "Ρυθμίσεις εφαρμογής",
      'notifications_section': "Ειδοποιήσεις",
      'privacy_security_section': "Απόρρητο και ασφάλεια",
      'account_section': "Λογαριασμός",
      '6-Digit Code': "6-ψήφιος κωδικός",
    },
    'pl': {
      'enable_notifications': "Włącz powiadomienia",
      'dark_mode': "Tryb ciemny",
      'light_mode': "Tryb jasny",
      'select_language_hint': "Wybierz język",
      'select_currency_hint': "Wybierz walutę",
      'font_size': "Rozmiar czcionki",
      'privacy_mode': "Tryb prywatności",
      'accent_color_hint': "Kolor akcentu",
      'notification_sound_hint': "Dźwięk powiadomienia",
      'layout_mode_hint': "Tryb układu",
      'privacy_policy_button': "Polityka prywatności",
      'terms_conditions_button': "Regulamin",
      'about_button': "O aplikacji",
      'logout_button': "Wyloguj się",
      'username_button': "Nazwa użytkownika",
      'email_button': "E-mail",
      'profile_settings_section': "Ustawienia profilu",
      'app_settings_section': "Ustawienia aplikacji",
      'notifications_section': "Powiadomienia",
      'privacy_security_section': "Prywatność i bezpieczeństwo",
      'account_section': "Konto",
      '6-Digit Code': "Kod 6-cyfrowy",
    },
    'vi': {
      'enable_notifications': "Bật thông báo",
      'dark_mode': "Chế độ tối",
      'light_mode': "Chế độ sáng",
      'select_language_hint': "Chọn ngôn ngữ",
      'select_currency_hint': "Chọn tiền tệ",
      'font_size': "Kích thước phông chữ",
      'privacy_mode': "Chế độ bảo mật",
      'accent_color_hint': "Màu điểm nhấn",
      'notification_sound_hint': "Âm thanh thông báo",
      'layout_mode_hint': "Chế độ bố cục",
      'privacy_policy_button': "Chính sách bảo mật",
      'terms_conditions_button': "Điều khoản và điều kiện",
      'about_button': "Giới thiệu",
      'logout_button': "Đăng xuất",
      'username_button': "Tên người dùng",
      'email_button': "Email",
      'profile_settings_section': "Cài đặt hồ sơ",
      'app_settings_section': "Cài đặt ứng dụng",
      'notifications_section': "Thông báo",
      'privacy_security_section': "Bảo mật và riêng tư",
      'account_section': "Tài khoản",
      '6-Digit Code': "Mã 6 chữ số",
    },

    // Other language sections follow the same pattern...
  };
  static String getLabel(String languageCode, String key) {
    return localizedValues[languageCode]?[key] ?? key;
  }
}
