class PageTitles {
  static Map<String, Map<String, String>> titles = {
    // English (en)
    'en': {
      'home_page_title': 'Donations',
      'sign_in_title': 'Sign In',
      'sign_up_title': 'Sign Up',
      'profile_page_title': 'Profile',
      'about_us_page_title': 'About Us',
      'feedback_page_title': 'Feedback',
      'settings_page_title': 'Settings',
      'help_support_page_title': 'Help & Support',
      'partners_page_title': 'Partners',
      'privacy_security_page_title': 'Privacy & Security',
      'terms_conditions_page_title': 'Terms & Conditions',
    },
    // Spanish (es)
    'es': {
      'home_page_title': 'Donaciones',
      'sign_in_title': 'Iniciar Sesión',
      'sign_up_title': 'Registrarse',
      'profile_page_title': 'Perfil',
      'about_us_page_title': 'Sobre Nosotros',
      'feedback_page_title': 'Comentarios',
      'settings_page_title': 'Configuración',
      'help_support_page_title': 'Ayuda y Soporte',
      'partners_page_title': 'Socios',
      'privacy_security_page_title': 'Privacidad y Seguridad',
      'terms_conditions_page_title': 'Términos y Condiciones',
    },
    // French (fr)
    'fr': {
      'home_page_title': 'Dons',
      'sign_in_title': 'Se Connecter',
      'sign_up_title': 'S\'inscrire',
      'profile_page_title': 'Profil',
      'about_us_page_title': 'À Propos de Nous',
      'feedback_page_title': 'Retour d’Information',
      'settings_page_title': 'Paramètres',
      'help_support_page_title': 'Aide & Support',
      'partners_page_title': 'Partenaires',
      'privacy_security_page_title': 'Confidentialité & Sécurité',
      'terms_conditions_page_title': 'Conditions Générales',
    },
    // German (de)
    'de': {
      'home_page_title': 'Spenden',
      'sign_in_title': 'Anmelden',
      'sign_up_title': 'Registrieren',
      'profile_page_title': 'Profil',
      'about_us_page_title': 'Über Uns',
      'feedback_page_title': 'Feedback',
      'settings_page_title': 'Einstellungen',
      'help_support_page_title': 'Hilfe & Support',
      'partners_page_title': 'Partner',
      'privacy_security_page_title': 'Datenschutz & Sicherheit',
      'terms_conditions_page_title': 'Geschäftsbedingungen',
    },
    // Italian (it)
    'it': {
      'home_page_title': 'Donazioni',
      'sign_in_title': 'Accedi',
      'sign_up_title': 'Registrati',
      'profile_page_title': 'Profilo',
      'about_us_page_title': 'Chi Siamo',
      'feedback_page_title': 'Feedback',
      'settings_page_title': 'Impostazioni',
      'help_support_page_title': 'Aiuto & Supporto',
      'partners_page_title': 'Partner',
      'privacy_security_page_title': 'Privacy & Sicurezza',
      'terms_conditions_page_title': 'Termini e Condizioni',
    },
    // Portuguese (pt)
    'pt': {
      'home_page_title': 'Doações',
      'sign_in_title': 'Entrar',
      'sign_up_title': 'Cadastrar-se',
      'profile_page_title': 'Perfil',
      'about_us_page_title': 'Sobre Nós',
      'feedback_page_title': 'Feedback',
      'settings_page_title': 'Configurações',
      'help_support_page_title': 'Ajuda & Suporte',
      'partners_page_title': 'Parceiros',
      'privacy_security_page_title': 'Privacidade & Segurança',
      'terms_conditions_page_title': 'Termos & Condições',
    },
    // Dutch (nl)
    'nl': {
      'home_page_title': 'Donaties',
      'sign_in_title': 'Inloggen',
      'sign_up_title': 'Registreren',
      'profile_page_title': 'Profiel',
      'about_us_page_title': 'Over Ons',
      'feedback_page_title': 'Feedback',
      'settings_page_title': 'Instellingen',
      'help_support_page_title': 'Help & Ondersteuning',
      'partners_page_title': 'Partners',
      'privacy_security_page_title': 'Privacy & Beveiliging',
      'terms_conditions_page_title': 'Algemene Voorwaarden',
    },
    // Russian (ru)
    'ru': {
      'home_page_title': 'Пожертвования',
      'sign_in_title': 'Войти',
      'sign_up_title': 'Зарегистрироваться',
      'profile_page_title': 'Профиль',
      'about_us_page_title': 'О Нас',
      'feedback_page_title': 'Обратная связь',
      'settings_page_title': 'Настройки',
      'help_support_page_title': 'Помощь и Поддержка',
      'partners_page_title': 'Партнеры',
      'privacy_security_page_title': 'Конфиденциальность и Безопасность',
      'terms_conditions_page_title': 'Условия использования',
    },
    // Chinese (zh)
    'zh': {
      'home_page_title': '捐款',
      'sign_in_title': '登录',
      'sign_up_title': '注册',
      'profile_page_title': '个人资料',
      'about_us_page_title': '关于我们',
      'feedback_page_title': '反馈',
      'settings_page_title': '设置',
      'help_support_page_title': '帮助与支持',
      'partners_page_title': '合作伙伴',
      'privacy_security_page_title': '隐私与安全',
      'terms_conditions_page_title': '条款与条件',
    },
    // Japanese (ja)
    'ja': {
      'home_page_title': '寄付',
      'sign_in_title': 'サインイン',
      'sign_up_title': 'サインアップ',
      'profile_page_title': 'プロフィール',
      'about_us_page_title': '私たちに関しては',
      'feedback_page_title': 'フィードバック',
      'settings_page_title': '設定',
      'help_support_page_title': 'ヘルプ＆サポート',
      'partners_page_title': 'パートナー',
      'privacy_security_page_title': 'プライバシー＆セキュリティ',
      'terms_conditions_page_title': '利用規約',
    },
    // Korean (ko)
    'ko': {
      'home_page_title': '기부',
      'sign_in_title': '로그인',
      'sign_up_title': '회원가입',
      'profile_page_title': '프로필',
      'about_us_page_title': '회사 소개',
      'feedback_page_title': '피드백',
      'settings_page_title': '설정',
      'help_support_page_title': '도움말 및 지원',
      'partners_page_title': '파트너',
      'privacy_security_page_title': '개인정보 및 보안',
      'terms_conditions_page_title': '이용 약관',
    },
    // Arabic (ar)
    'ar': {
      'home_page_title': 'التبرعات',
      'sign_in_title': 'تسجيل الدخول',
      'sign_up_title': 'إنشاء حساب',
      'profile_page_title': 'الملف الشخصي',
      'about_us_page_title': 'من نحن',
      'feedback_page_title': 'الملاحظات',
      'settings_page_title': 'الإعدادات',
      'help_support_page_title': 'المساعدة والدعم',
      'partners_page_title': 'الشركاء',
      'privacy_security_page_title': 'الخصوصية والأمان',
      'terms_conditions_page_title': 'الشروط والأحكام',
    },
    // Hindi (hi)
    'hi': {
      'home_page_title': 'दान',
      'sign_in_title': 'साइन इन करें',
      'sign_up_title': 'साइन अप करें',
      'profile_page_title': 'प्रोफ़ाइल',
      'about_us_page_title': 'हमारे बारे में',
      'feedback_page_title': 'प्रतिक्रिया',
      'settings_page_title': 'सेटिंग्स',
      'help_support_page_title': 'सहायता और समर्थन',
      'partners_page_title': 'साझेदार',
      'privacy_security_page_title': 'गोपनीयता और सुरक्षा',
      'terms_conditions_page_title': 'नियम और शर्तें',
    },
    // Turkish (tr)
    'tr': {
      'home_page_title': 'Bağışlar',
      'sign_in_title': 'Oturum Aç',
      'sign_up_title': 'Kayıt Ol',
      'profile_page_title': 'Profil',
      'about_us_page_title': 'Hakkımızda',
      'feedback_page_title': 'Geri Bildirim',
      'settings_page_title': 'Ayarlar',
      'help_support_page_title': 'Yardım & Destek',
      'partners_page_title': 'Ortaklar',
      'privacy_security_page_title': 'Gizlilik & Güvenlik',
      'terms_conditions_page_title': 'Şartlar & Koşullar',
    },
    // Thai (th)
    'th': {
      'home_page_title': 'การบริจาค',
      'sign_in_title': 'เข้าสู่ระบบ',
      'sign_up_title': 'สมัครสมาชิก',
      'profile_page_title': 'โปรไฟล์',
      'about_us_page_title': 'เกี่ยวกับเรา',
      'feedback_page_title': 'ข้อเสนอแนะ',
      'settings_page_title': 'การตั้งค่า',
      'help_support_page_title': 'ช่วยเหลือ & สนับสนุน',
      'partners_page_title': 'พันธมิตร',
      'privacy_security_page_title': 'ความเป็นส่วนตัว & ความปลอดภัย',
      'terms_conditions_page_title': 'ข้อกำหนด & เงื่อนไข',
    },
    // Swedish (sv)
    'sv': {
      'home_page_title': 'Donationer',
      'sign_in_title': 'Logga In',
      'sign_up_title': 'Registrera',
      'profile_page_title': 'Profil',
      'about_us_page_title': 'Om Oss',
      'feedback_page_title': 'Feedback',
      'settings_page_title': 'Inställningar',
      'help_support_page_title': 'Hjälp & Support',
      'partners_page_title': 'Partners',
      'privacy_security_page_title': 'Sekretess & Säkerhet',
      'terms_conditions_page_title': 'Villkor',
    },
    // Greek (el)
    'el': {
      'home_page_title': 'Δωρεές',
      'sign_in_title': 'Σύνδεση',
      'sign_up_title': 'Εγγραφή',
      'profile_page_title': 'Προφίλ',
      'about_us_page_title': 'Σχετικά με εμάς',
      'feedback_page_title': 'Ανατροφοδότηση',
      'settings_page_title': 'Ρυθμίσεις',
      'help_support_page_title': 'Βοήθεια & Υποστήριξη',
      'partners_page_title': 'Συνεργάτες',
      'privacy_security_page_title': 'Απόρρητο & Ασφάλεια',
      'terms_conditions_page_title': 'Όροι & Προϋποθέσεις',
    },
    // Polish (pl)
    'pl': {
      'home_page_title': 'Darowizny',
      'sign_in_title': 'Zaloguj się',
      'sign_up_title': 'Zarejestruj się',
      'profile_page_title': 'Profil',
      'about_us_page_title': 'O Nas',
      'feedback_page_title': 'Opinie',
      'settings_page_title': 'Ustawienia',
      'help_support_page_title': 'Pomoc i Wsparcie',
      'partners_page_title': 'Partnerzy',
      'privacy_security_page_title': 'Prywatność i Bezpieczeństwo',
      'terms_conditions_page_title': 'Regulamin',
    },
    // Vietnamese (vi)
    'vi': {
      'home_page_title': 'Quyên góp',
      'sign_in_title': 'Đăng nhập',
      'sign_up_title': 'Đăng ký',
      'profile_page_title': 'Hồ sơ',
      'about_us_page_title': 'Về chúng tôi',
      'feedback_page_title': 'Phản hồi',
      'settings_page_title': 'Cài đặt',
      'help_support_page_title': 'Trợ giúp & Hỗ trợ',
      'partners_page_title': 'Đối tác',
      'privacy_security_page_title': 'Riêng tư & Bảo mật',
      'terms_conditions_page_title': 'Điều khoản & Điều kiện',
    },
  };

  static String getTitle(String langCode, String key) {
    return titles[langCode]?[key] ?? key;
  }
}

